import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  static const String _langKey = 'selected_language';
  String _currentLang = 'en';

  final Map<String, Map<String, String>> _translations = {
    'en': {
      'vownote': 'BizLedger',
      'search': 'Search bookings...',
      'no_bookings': 'No bookings found',
      'completed': 'Completed',
      'address': 'Address',
      'phone': 'Phone',
      'dates': 'Dates',
      'total': 'Total Amount',
      'received': 'Total Received',
      'due': 'Final Balance',
      'done': 'Done',
      'delete': 'Delete',
      'export_pdf': 'Export Monthly PDF',
      'customer': 'Customer',
      'settings': 'Settings',
      'language': 'Language',
      'money_in_pdf': 'Show Money in PDF',
      'help_center': 'Beginner Help Centre',
      'help_text':
          'Learn how to use BizLedger professionally. Track your marriage bookings, manage advances, and generate PDF reports for your studio.',
      'bride': 'Bride Name',
      'groom': 'Groom Name',
      'alt_phone': 'Alternative Phone',
      'notes': 'Special Notes',
      'total_adv': 'Total Advance',
      'adv_received': 'Advance Received',
      'adv_pending': 'Advance Pending',
      'diary_mgmt': 'Diary Management',
      'category': 'Booking Type',
      'male': 'Male',
      'female': 'Female',
      'diary_code': 'Diary Code (Optional)',
      'diary_ref': 'Diary Ref',
      'save_booking': 'Save Booking',
      'export_settings': 'Export Settings',
      'show_names': 'Show Names in Export',
      'show_phone': 'Show Phone in Export',
      'show_address': 'Show Address in Export',
      'show_diary': 'Show Diary Ref in Export',
      'screenshot_4k': 'Professional 4K Snapshots',
      'share_image': 'Share as Image',
      'full_report': 'Generate Full Report (All Time)',
      'generating_pdf': 'Generating Professional PDF...',
      'app': 'App',
    },
    'ml': {
      'vownote': 'BizLedger',
      'search': 'ബുക്കിംഗുകൾ തിരയുക...',
      'no_bookings': 'ബുക്കിംഗുകൾ ലഭ്യമല്ല',
      'completed': 'പൂർത്തിയായി',
      'address': 'വിലാസം',
      'phone': 'ഫോൺ',
      'dates': 'തിയതികൾ',
      'total': 'ആകെ തുക',
      'received': 'ആകെ ലഭിച്ചത്',
      'due': 'അവസാന ബാക്കി',
      'done': 'പൂർത്തിയായി',
      'delete': 'ഡിലീറ്റ്',
      'export_pdf': 'പ്രതിമാസ PDF',
      'customer': 'കസ്റ്റമർ',
      'settings': 'സെറ്റിംഗ്സ്',
      'language': 'ഭാഷ',
      'money_in_pdf': 'PDF-ൽ തുക കാണിക്കുക',
      'help_center': 'ഹെൽപ് സെന്റർ',
      'help_text':
          'BizLedger എങ്ങനെ പ്രൊഫഷണലായി ഉപയോഗിക്കാം എന്ന് മനസ്സിലാക്കുക. നിങ്ങളുടെ വിവാഹ ബുക്കിംഗുകൾ ട്രാക്ക് ചെയ്യാനും അഡ്വാൻസ് മാനേജ് ചെയ്യാനും സ്റ്റുഡിയോ റിപ്പോർട്ടുകൾ തയ്യാറാക്കാനും ഇത് സഹായിക്കുന്നു.',
      'bride': 'വധുവിന്റെ പേര്',
      'groom': 'വരന്റെ പേര്',
      'alt_phone': 'മറ്റൊരു ഫോൺ നമ്പർ',
      'notes': 'പ്രത്യേക കുറിപ്പുകൾ',
      'total_adv': 'ആകെ അഡ്വാൻസ്',
      'adv_received': 'ലഭിച്ച അഡ്വാൻസ്',
      'adv_pending': 'അഡ്വാൻസ് ബാക്കി',
      'diary_mgmt': 'ഡയറി മാനേജ്‌മെന്റ്',
      'category': 'ബുക്കിംഗ് വിഭാഗം',
      'male': 'പുരുഷൻ',
      'female': 'സ്ത്രീ',
      'diary_code': 'ഡയറി കോഡ്',
      'diary_ref': 'ഡയറി റെഫ്',
      'save_booking': 'ബുക്കിംഗ് സേവ് ചെയ്യുക',
      'export_settings': 'എക്സ്പോർട്ട് സെറ്റിംഗ്സ്',
      'show_names': 'പേരുകൾ എക്സ്പോർട്ടിൽ കാണിക്കുക',
      'show_phone': 'ഫോൺ നമ്പർ എക്സ്പോർട്ടിൽ കാണിക്കുക',
      'show_address': 'വിലാസം എക്സ്പോർട്ടിൽ കാണിക്കുക',
      'show_diary': 'ഡയറി റെഫ് എക്സ്പോർട്ടിൽ കാണിക്കുക',
      'screenshot_4k': 'പ്രൊഫഷണൽ 4K സ്ക്രീൻഷോട്ട്',
      'share_image': 'ചിത്രമായി ഷെയർ ചെയ്യുക',
      'full_report': 'സമ്പൂർണ്ണ റിപ്പോർട്ട് (എല്ലാ മാസവും)',
      'generating_pdf': 'പ്രൊഫഷണൽ PDF തയ്യാറാക്കുന്നു...',
      'app': 'ആപ്പ്',
    },
    'hi': {
      'vownote': 'BizLedger',
      'search': 'बुकिंग खोजें...',
      'no_bookings': 'कोई बुकिंग नहीं मिली',
      'completed': 'पूर्ण',
      'address': 'पता',
      'phone': 'फ़ोन',
      'dates': 'तिथियाँ',
      'total': 'कुल राशि',
      'received': 'प्राप्त',
      'due': 'बकाया',
      'done': 'हो गया',
      'delete': 'मिटाएं',
      'export_pdf': 'मासिक PDF निर्यात करें',
      'customer': 'ग्राहक',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'money_in_pdf': 'PDF में पैसा दिखाएं',
      'help_center': 'सहायता केंद्र',
      'help_text': 'बुकिंग ट्रैक करें और रिपोर्ट बनाएं',
      'bride': 'दुल्हन का नाम',
      'groom': 'दूल्हे का नाम',
      'alt_phone': 'वैकल्पिक फ़ोन',
      'notes': 'विशेष नोट्स',
      'total_adv': 'कुल अग्रिम',
      'adv_received': 'प्राप्त अग्रिम',
      'adv_pending': 'बकाया अग्रिम',
      'app': ' ऐप',
    },
    'ta': {
      'vownote': 'BizLedger',
      'search': 'பதிவுகளைத் தேடு...',
      'no_bookings': 'பதிவுகள் இல்லை',
      'completed': 'முடிந்தது',
      'address': 'முகவரி',
      'phone': 'தொலைபேசி',
      'dates': 'தேதிகள்',
      'total': 'மொத்த தொகை',
      'received': 'பெறப்பட்டது',
      'due': 'நிலுவை',
      'done': 'முடிந்தது',
      'delete': 'நீக்கு',
      'export_pdf': 'மாதாந்திர PDF',
      'customer': 'வாடிக்கையாளர்',
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'money_in_pdf': 'PDF-இல் பணம் காட்டு',
      'help_center': 'உதவி மையம்',
      'help_text': 'பதிவுகளைக் கண்காணித்து அறிக்கைகளை உருவாக்கவும்',
      'bride': 'மணமகள் பெயர்',
      'groom': 'மணமகன் பெயர்',
      'app': 'பயன்பாடு',
    },
    'es': {
      'vownote': 'BizLedger',
      'search': 'Buscar reservas...',
      'no_bookings': 'No se encontraron reservas',
      'completed': 'Completado',
      'address': 'Dirección',
      'phone': 'Teléfono',
      'dates': 'Fechas',
      'total': 'Total',
      'received': 'Recibido',
      'due': 'Pendiente',
      'done': 'Listo',
      'delete': 'Eliminar',
      'export_pdf': 'Exportar PDF mensual',
      'customer': 'Cliente',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'money_in_pdf': 'Mostrar dinero en PDF',
      'help_center': 'Centro de ayuda',
      'help_text': 'Realiza seguimiento de reservas y genera informes',
      'bride': 'Novia',
      'groom': 'Novio',
      'app': 'Aplicación',
    },
    'fr': {
      'vownote': 'BizLedger',
      'search': 'Rechercher des réservations...',
      'no_bookings': 'Aucune réservation trouvée',
      'completed': 'Terminé',
      'address': 'Adresse',
      'phone': 'Téléphone',
      'dates': 'Dates',
      'total': 'Total',
      'received': 'Reçu',
      'due': 'Dû',
      'done': 'Fait',
      'delete': 'Supprimer',
      'export_pdf': 'Exporter PDF mensuel',
      'customer': 'Client',
      'settings': 'Paramètres',
      'language': 'Langue',
      'money_in_pdf': 'Afficher montant en PDF',
      'help_center': 'Centre d\'aide',
      'help_text': 'Suivez les réservations et générez des rapports',
      'bride': 'Mariée',
      'groom': 'Marié',
      'app': 'Application',
    },
    'ar': {
      'vownote': 'BizLedger',
      'search': 'البحث عن الحجوزات...',
      'no_bookings': 'لم يتم العثور على حجوزات',
      'completed': 'مكتمل',
      'address': 'العنوان',
      'phone': 'الهاتف',
      'dates': 'التواريخ',
      'total': 'المجموع',
      'received': 'المستلم',
      'due': 'المستحق',
      'done': 'تم',
      'delete': 'حذف',
      'export_pdf': 'تصدير PDF شهري',
      'customer': 'العميل',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'money_in_pdf': 'إظهار المبلغ في PDF',
      'help_center': 'مركز المساعدة',
      'help_text': 'تتبع الحجوزات وإنشاء التقارير',
      'bride': 'العروس',
      'groom': 'العريس',
      'app': 'التطبيق',
    },
    'de': {
      'vownote': 'BizLedger',
      'search': 'Buchungen suchen...',
      'no_bookings': 'Keine Buchungen gefunden',
      'completed': 'Abgeschlossen',
      'address': 'Adresse',
      'phone': 'Telefon',
      'dates': 'Termine',
      'total': 'Gesamt',
      'received': 'Erhalten',
      'due': 'Fällig',
      'done': 'Fertig',
      'delete': 'Löschen',
      'export_pdf': 'Monatliches PDF exportieren',
      'customer': 'Kunde',
      'settings': 'Einstellungen',
      'language': 'Sprache',
      'money_in_pdf': 'Geld in PDF anzeigen',
      'help_center': 'Hilfezentrum',
      'help_text': 'Buchungen verfolgen und Berichte erstellen',
      'bride': 'Braut',
      'groom': 'Bräutigam',
      'app': 'App',
    },
    'id': {
      'vownote': 'BizLedger',
      'search': 'Cari pemesanan...',
      'no_bookings': 'Tidak ada pemesanan ditemukan',
      'completed': 'Selesai',
      'address': 'Alamat',
      'phone': 'Telepon',
      'dates': 'Tanggal',
      'total': 'Total',
      'received': 'Diterima',
      'due': 'Jatuh tempo',
      'done': 'Selesai',
      'delete': 'Hapus',
      'export_pdf': 'Ekspor PDF bulanan',
      'customer': 'Pelanggan',
      'settings': 'Pengaturan',
      'language': 'Bahasa',
      'money_in_pdf': 'Tampilkan uang di PDF',
      'help_center': 'Pusat bantuan',
      'help_text': 'Lacak pemesanan dan buat laporan',
      'bride': 'Pengantin Wanita',
      'groom': 'Pengantin Pria',
      'app': 'Aplikasi',
    },
    'pt': {
      'vownote': 'BizLedger',
      'search': 'Pesquisar reservas...',
      'no_bookings': 'Nenhuma reserva encontrada',
      'completed': 'Concluído',
      'address': 'Endereço',
      'phone': 'Telefone',
      'dates': 'Datas',
      'total': 'Total',
      'received': 'Recebido',
      'due': 'Devido',
      'done': 'Concluído',
      'delete': 'Excluir',
      'export_pdf': 'Exportar PDF mensal',
      'customer': 'Cliente',
      'settings': 'Configurações',
      'language': 'Idioma',
      'money_in_pdf': 'Mostrar valor no PDF',
      'help_center': 'Central de ajuda',
      'help_text': 'Rastreie reservas e gere relatórios',
      'bride': 'Noiva',
      'groom': 'Noivo',
      'app': 'Aplicativo',
    },
  };

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLang = prefs.getString(_langKey) ?? 'en';
  }

  String get currentLanguage => _currentLang;

  Future<void> setLanguage(String lang) async {
    _currentLang = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_langKey, lang);
  }

  String tr(String key) {
    return _translations[_currentLang]?[key] ?? key;
  }
}

String tr(String key) => LocalizationService().tr(key);
