import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  static const String _langKey = 'selected_language';
  String _currentLang = 'en';

  final Map<String, Map<String, String>> _translations = {
    'en': {
      'Wedding Studio': 'Wedding Studio',
      'Photography Studio': 'Photography Studio',
      'Catering Service': 'Catering Service',
      'Event Planning': 'Event Planning',
      'General Business': 'General Business',
      'Wedding Report': 'Wedding Report',
      'Photography Report': 'Photography Report',
      'Catering Report': 'Catering Report',
      'Event Report': 'Event Report',
      'Business Report': 'Business Report',
      'Wedding Dates': 'Wedding Dates',
      'Session Dates': 'Session Dates',
      'Service Dates': 'Service Dates',
      'Event Dates': 'Event Dates',
      'Wedding Date': 'Wedding Date',
      'Session Date': 'Session Date',
      'Service Date': 'Service Date',
      'Event Date': 'Event Date',
      'Partner Name': 'Partner Name',
      'Contact Person': 'Contact Person',
      'Secondary Contact': 'Secondary Contact',
      'Organizer': 'Organizer',
      'Co-Organizer': 'Co-Organizer',
      'No weddings booked yet.\nTap + to create your first booking.': 'No weddings booked yet.\nTap + to create your first booking.',
      'No photoshoots booked yet.\nTap + to schedule your first session.': 'No photoshoots booked yet.\nTap + to schedule your first session.',
      'No catering orders yet.\nTap + to add your first booking.': 'No catering orders yet.\nTap + to add your first booking.',
      'No events planned yet.\nTap + to create your first event.': 'No events planned yet.\nTap + to create your first event.',
      'No bookings yet.\nTap + to create your first booking.': 'No bookings yet.\nTap + to create your first booking.',
      'add_date': 'Add Date',
      'required': 'Required',
      'gdrive_sync': 'Google Drive Sync',
      'gdrive_desc': 'Backup your database securely to your personal Google Drive (AppData)',
      'sign_in_google': 'Sign in with Google',
      'sign_out': 'Sign Out',
      'backup_to_drive': 'Backup to Drive',
      'restore_from_drive': 'Restore from Drive',
      'connected_as': 'Connected as',
      'backup_success': 'Backup uploaded successfully!',
      'restore_success': 'Restore completed! Please restart the app.',
      'error_backup': 'Backup failed',
      'error_restore': 'Restore failed',
      'business_type': 'Business Type',

      'delete_booking_q': 'Delete Booking?',
      'no_image_card': 'NO IMAGE CARD',
      'due': 'Due',
      'paid': 'Paid',
      'booking_confirmed_title': 'Booking Confirmed',
      'not_applicable': 'N/A',
      'address': 'Address',
      'contact': 'Contact',
      'financials': 'Financials',
      'total': 'Total',
      'received': 'Received',
      'thank_you': 'Thank you',
      'selected': 'Selected',
      'auth_reason': 'Authenticate to access BizLedger',
      'face_id': 'Face ID',
      'fingerprint': 'Fingerprint',
      'iris': 'Iris',
      'biometric': 'Biometric',

      'select_business_type': 'Select Business Type',
      'BUSINESS': 'BUSINESS',
      'APPEARANCE': 'APPEARANCE',
      'dark_mode': 'Dark Mode',
      'ABOUT': 'ABOUT',
      'version': 'Version',
      'privacy_policy': 'Privacy Policy',
      'licenses': 'Licenses',
      'github': 'GitHub',
      'EXPORT': 'EXPORT',
      'manage_pdf_layout': 'Manage PDF layout & quality',
      'SECURITY': 'SECURITY',
      'app_lock_biometrics': 'App Lock (Biometrics)',
      'enable_biometric': 'Enable fingerprint or face unlock',
      'biometrics_unavailable': 'Biometrics not available on this device',
      'BACKUP & SYNC': 'BACKUP & SYNC',
      'export_backup': 'Export Backup',
      'import_backup': 'Import Backup',
      'auto_backup': 'Auto Backup',
      'import_backup_warning': 'This will merge bookings with current list.',
      'HELP': 'HELP',
      'fps_monitor': 'FPS Monitor',
      'promotion_120hz': 'ProMotion (120Hz)',
      'saved_successfully': 'Saved Successfully',
      'customer_information': 'Customer Information',
      'finance_details': 'Finance details',
      'business_insights': 'Business Insights',
      'monthly_performance': 'Monthly Performance',
      'total_valuation': 'TOTAL VALUATION',
      'events_count': 'Events',
      'collected': 'Collected',
      'outstanding': 'Outstanding',

      'Bride': 'Bride',
      'Groom': 'Groom',
      'BizLedger': 'BizLedger',
      'PhotoLedger': 'PhotoLedger',
      'FoodLedger': 'FoodLedger',
      'EventLedger': 'EventLedger',
      'Ledger': 'Ledger',
      'Wedding Studio': 'Wedding Studio',
      'Photography Studio': 'Photography Studio',
      'Catering Service': 'Catering Service',
      'Event Planning': 'Event Planning',
      'General Business': 'General Business',
      'Wedding Dates': 'Wedding Dates',
      'Session Dates': 'Session Dates',
      'Event Dates': 'Event Dates',
      'Service Dates': 'Service Dates',
      'Wedding Date': 'Wedding Date',
      'Session Date': 'Session Date',
      'Event Date': 'Event Date',
      'Service Date': 'Service Date',
      'Client': 'Client',
      'Customer': 'Customer',
      'Client 1': 'Client 1',
      'Client 2': 'Client 2',
      'Contact': 'Contact',
      'Contact 2': 'Contact 2',
      'Wedding Report': 'Wedding Report',
      'Photography Report': 'Photography Report',
      'Catering Report': 'Catering Report',
      'Event Report': 'Event Report',
      'General Report': 'General Report',
      'No weddings booked yet. Add your first wedding!': 'No weddings booked yet. Add your first wedding!',
      'No sessions booked yet. Add your first session!': 'No sessions booked yet. Add your first session!',
      'No events booked yet. Add your first event!': 'No events booked yet. Add your first event!',
      'No records found. Add your first record!': 'No records found. Add your first record!',

      'delete_bookings': 'Delete Bookings?',
      'cannot_undo': 'This action cannot be undone.',
      'cancel': 'Cancel',
      'share_text': 'Share Text (WhatsApp/Other)',
      'share_image_card': 'Share Card Image',
      'change_to': 'Change to',
      'change': 'Change',
      'business_changed': 'Business type changed to',
      'restore_backup': 'Restore Backup?',
      'import': 'Import',
      'enable': 'Enable',
      'developer_options': 'Developer Options',
      'close': 'Close',
      'contact_details': 'Contact details',
      'select_wedding_dates': 'Please select wedding dates',
      'internal_notes': 'Internal notes...',
      'advance_paid': 'Advance Paid',
      'pending': 'Pending',
      'saved': 'Saved!',
      'new_booking': 'New Booking',
      'edit_booking': 'Edit Booking',
      'error': 'Error',

      'app_locked': 'App Locked',
      'authenticating': 'Authenticating...',
      'unlock_continue': 'Unlock to continue',
      'tap_to_unlock': 'Tap to Unlock with',

      'help_create_title': 'Creating a Booking',
      'help_create_content': 'Tap the + button to create a new booking. Fill in customer details, event dates, and financial information.',
      'help_create_step1': 'Tap the floating + button on the home screen',
      'help_create_step2': 'Enter customer name (required)',
      'help_create_step3': 'Select event dates using the calendar',
      'help_create_step4': 'Add financial details (total, advance, payments)',
      'help_create_step5': 'Tap DONE to save',
      'help_biz_title': 'Business Types',
      'help_biz_content': 'BizLedger supports multiple business types. Each type customizes the app with appropriate terminology.',
      'help_biz_step1': 'Go to Settings → Business Type',
      'help_biz_step2': 'Choose from Wedding, Photography, Catering, Events, or General',
      'help_biz_step3': 'Confirm your selection',
      'help_calc_title': 'Advanced Calculations',
      'help_calc_content': 'Track payments with detailed calculations including tax, discounts, and multiple payment methods.',
      'help_calc_step1': 'In booking form, add total amount',
      'help_calc_step2': 'Add advance and received amounts',
      'help_calc_step3': 'App auto-calculates pending',
      'help_share_title': 'Sharing & Export',
      'help_share_content': 'Export bookings as images or PDFs. Customize what information appears in exports from Settings.',
      'help_share_step1': 'Open any booking',
      'help_share_step2': 'Tap share icon',
      'help_share_step3': 'Choose export format',
      'help_dark_title': 'Dark Mode',
      'help_dark_content': 'Switch between light and dark themes with optimized animations.',
      'help_dark_step1': 'Go to Settings',
      'help_dark_step2': 'Toggle "Dark Mode"',
      'help_backup_title': 'Backup & Restore',
      'help_backup_content': 'Securely back up your bookings locally or sync them to Google Drive.',
      'help_backup_step1': 'Go to Settings > Backup & Sync',
      'help_backup_step2': 'Tap "Export Backup" to save data to your device\'s Documents folder.',
      'help_backup_step3': 'Tap "Backup to Drive" to upload and save your data securely in the cloud.',
      'help_backup_step4': 'To restore, click "Import" or "Restore from Drive". The app will automatically reload.',
      'vownote': 'BizLedger',
      'search': 'Search bookings...',
      'no_bookings': 'No bookings found',
      'completed': 'Completed',
      'address': 'Address',
      'phone': 'Phone',
      'dates': 'Dates',
      'total': 'Total Amount',
      'received': 'Total Received',
      'due': 'Final Balance',
      'done': 'Done',
      'delete': 'Delete',
      'export_pdf': 'Export Monthly PDF',
      'customer': 'Customer',
      'settings': 'Settings',
      'language': 'Language',
      'money_in_pdf': 'Show Money in PDF',
      'help_center': 'Beginner Help Centre',
      'help_text': 'Learn how to use BizLedger professionally. Track your marriage bookings, manage advances, and generate PDF reports for your studio.',
      'bride': 'Bride Name',
      'groom': 'Groom Name',
      'alt_phone': 'Alternative Phone',
      'notes': 'Special Notes',
      'total_adv': 'Total Advance',
      'adv_received': 'Advance Received',
      'adv_pending': 'Advance Pending',
      'diary_mgmt': 'Diary Management',
      'category': 'Booking Type',
      'male': 'Male',
      'female': 'Female',
      'diary_code': 'Diary Code (Optional)',
      'diary_ref': 'Diary Ref',
      'save_booking': 'Save Booking',
      'export_settings': 'Export Settings',
      'show_names': 'Show Names in Export',
      'show_phone': 'Show Phone in Export',
      'show_address': 'Show Address in Export',
      'show_diary': 'Show Diary Ref in Export',
      'screenshot_4k': 'Professional 4K Snapshots',
      'share_image': 'Share as Image',
      'full_report': 'Generate Full Report (All Time)',
      'generating_pdf': 'Generating Professional PDF...',
      'app': 'App',
    },
    'ml': {
      'Wedding Studio': 'വെഡ്ഡിംഗ് സ്റ്റുഡിയോ',
      'Photography Studio': 'ഫോട്ടോഗ്രാഫി സ്റ്റുഡിയോ',
      'Catering Service': 'കേറ്ററിംഗ് സർവീസ്',
      'Event Planning': 'ഇവന്റ് പ്ലാനിംഗ്',
      'General Business': 'ജനറൽ ബിസിനസ്സ്',
      'Wedding Report': 'വെഡ്ഡിംഗ് റിപ്പോർട്ട്',
      'Photography Report': 'ഫോട്ടോഗ്രാഫി റിപ്പോർട്ട്',
      'Catering Report': 'കേറ്ററിംഗ് റിപ്പോർട്ട്',
      'Event Report': 'ഇവന്റ് റിപ്പോർട്ട്',
      'Business Report': 'ബിസിനസ്സ് റിപ്പോർട്ട്',
      'Wedding Dates': 'കല്യാണ തീയതികൾ',
      'Session Dates': 'സെഷൻ തീയതികൾ',
      'Service Dates': 'സർവീസ് തീയതികൾ',
      'Event Dates': 'ഇവന്റ് തീയതികൾ',
      'Wedding Date': 'കല്യാണ തീയതി',
      'Session Date': 'സെഷൻ തീയതി',
      'Service Date': 'സർവീസ് തീയതി',
      'Event Date': 'ഇവന്റ് തീയതി',
      'Partner Name': 'പങ്കാളിയുടെ പേര്',
      'Contact Person': 'ബന്ധപ്പെടേണ്ട വ്യക്തി',
      'Secondary Contact': 'മറ്റൊരു നമ്പർ',
      'Organizer': 'സംഘാടകൻ',
      'Co-Organizer': 'സഹ-സംഘാടകൻ',
      'No weddings booked yet.\nTap + to create your first booking.': 'വിവാഹങ്ങളൊന്നും ഇതുവരെ ബുക്ക് ചെയ്തിട്ടില്ല.\nആദ്യത്തെ ബുക്കിംഗ് സൃഷ്ടിക്കാൻ + ടാപ്പ് ചെയ്യുക.',
      'No photoshoots booked yet.\nTap + to schedule your first session.': 'ഫോട്ടോഷൂട്ടുകളൊന്നും ഇതുവരെ ബുക്ക് ചെയ്തിട്ടില്ല.\nനിങ്ങളുടെ ആദ്യ സെഷൻ ഷെഡ്യൂൾ ചെയ്യാൻ + ടാപ്പ് ചെയ്യുക.',
      'No catering orders yet.\nTap + to add your first booking.': 'കേറ്ററിംഗ് ഓർഡറുകളൊന്നും ഇതുവരെ ഇല്ല.\nആദ്യത്തെ ബുക്കിംഗ് ചേർക്കാൻ + ടാപ്പ് ചെയ്യുക.',
      'No events planned yet.\nTap + to create your first event.': 'ഇവന്റുകളൊന്നും ഇതുവരെ ആസൂത്രണം ചെയ്തിട്ടില്ല.\nനിങ്ങളുടെ ആദ്യ ഇവന്റ് സൃഷ്ടിക്കാൻ + ടാപ്പ് ചെയ്യുക.',
      'No bookings yet.\nTap + to create your first booking.': 'ബുക്കിംഗുകളൊന്നും ഇതുവരെ ഇല്ല.\nആദ്യത്തെ ബുക്കിംഗ് സൃഷ്ടിക്കാൻ + ടാപ്പ് ചെയ്യുക.',
      'add_date': 'തീയതി ചേർക്കുക',
      'required': 'ആവശ്യമാണ്',
      'gdrive_sync': 'ഗൂഗിൾ ഡ്രൈവ് സമന്വയം',
      'gdrive_desc': 'നിങ്ങളുടെ സ്വകാര്യ ഗൂഗിൾ ഡ്രൈവിലേക്ക് (AppData) സുരക്ഷിതമായി ബാക്കപ്പ് ചെയ്യുക',
      'sign_in_google': 'ഗൂഗിൾ ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക',
      'sign_out': 'ലോഗ് ഔട്ട് ചെയ്യുക',
      'backup_to_drive': 'ഡ്രൈവിലേക്ക് ബാക്കപ്പ് ചെയ്യുക',
      'restore_from_drive': 'ഡ്രൈവില് നിന്ന് പുനഃസ്ഥാപിക്കുക',
      'connected_as': 'കണക്ട് ചെയ്തിരിക്കുന്നത്',
      'backup_success': 'ബാക്കപ്പ് വിജയകരമായി അപ്‌ലോഡ് ചെയ്തു!',
      'restore_success': 'ബാക്കപ്പ് പുനഃസ്ഥാപിച്ചു! ദയവായി ആപ്പ് റീസ്റ്റാർട്ട് ചെയ്യുക.',
      'error_backup': 'ബാക്കപ്പ് പരാജയപ്പെട്ടു',
      'error_restore': 'പുനഃസ്ഥാപിക്കൽ പരാജയപ്പെട്ടു',
      'business_type': 'ബിസിനസ്സ് തരം',

      'delete_booking_q': 'ബുക്കിംഗ് ഇല്ലാതാക്കണോ?',
      'no_image_card': 'ഇമേജ് കാർഡ് ലഭ്യമല്ല',
      'due': 'ബാക്കി തുക',
      'paid': 'പണമടച്ചു',
      'booking_confirmed_title': 'ബുക്കിംഗ് ഉറപ്പിച്ചു',
      'not_applicable': 'ലഭ്യമല്ല',
      'address': 'വിലാസം',
      'contact': 'ബന്ധപ്പെടുക',
      'financials': 'സാമ്പത്തിക വിവരങ്ങൾ',
      'total': 'ആകെ',
      'received': 'ലഭിച്ചത്',
      'thank_you': 'നന്ദി',
      'selected': 'തിരഞ്ഞെടുത്തു',
      'auth_reason': 'ആപ്പ് തുറക്കാൻ ലോഗിൻ ചെയ്യുക',
      'face_id': 'ഫേസ് ഐഡി',
      'fingerprint': 'വിരലടയാളം',
      'iris': 'ഐറിസ്',
      'biometric': 'ബയോമെട്രിക്',

      'select_business_type': 'ബിസിനസ്സ് തരം തിരഞ്ഞെടുക്കുക',
      'BUSINESS': 'ബിസിനസ്സ്',
      'APPEARANCE': 'കാഴ്ച',
      'dark_mode': 'ഡാർക്ക് മോഡ്',
      'ABOUT': 'വിവരങ്ങൾ',
      'version': 'പതിപ്പ്',
      'privacy_policy': 'സ്വകാര്യതാ നയം',
      'licenses': 'ലൈസൻസുകൾ',
      'github': 'GitHub',
      'EXPORT': 'കയറ്റുമതി',
      'manage_pdf_layout': 'PDF ലേഔട്ടും ഗുണനിലവാരവും നിയന്ത്രിക്കുക',
      'SECURITY': 'സുരക്ഷ',
      'app_lock_biometrics': 'ആപ്പ് ലോക്ക് (ബയോമെട്രിക്സ്)',
      'enable_biometric': 'വിരലടയാളം അല്ലെങ്കിൽ ഫേസ് അൺലോക്ക് പ്രവർത്തനക്ഷമമാക്കുക',
      'biometrics_unavailable': 'ബയോമെട്രിക്സ് ഈ ഉപകരണത്തിൽ ലഭ്യമല്ല',
      'BACKUP & SYNC': 'ബാക്കപ്പും സമന്വയവും',
      'export_backup': 'ബാക്കപ്പ് എക്സ്പോർട്ട് ചെയ്യുക',
      'import_backup': 'ബാക്കപ്പ് ഇമ്പോർട്ട് ചെയ്യുക',
      'auto_backup': 'ഓട്ടോ ബാക്കപ്പ്',
      'import_backup_warning': 'ഇത് ബുക്കിംഗുകളെ നിലവിലെ ലിസ്റ്റുമായി ലയിപ്പിക്കും.',
      'HELP': 'സഹായം',
      'fps_monitor': 'FPS മോണിറ്റർ',
      'promotion_120hz': 'പ്രൊമോഷൻ (120Hz)',
      'saved_successfully': 'വിജയകരമായി സംരക്ഷിച്ചു',
      'customer_information': 'ഉപഭോക്താവിന്റെ വിവരങ്ങൾ',
      'finance_details': 'സാമ്പത്തിക വിവരങ്ങൾ',
      'business_insights': 'ബിസിനസ്സ് സ്ഥിതിവിവരക്കണക്കുകൾ',
      'monthly_performance': 'പ്രതിമാസ പ്രകടനം',
      'total_valuation': 'ആകെ മൂല്യം',
      'events_count': 'ഇവന്റുകൾ',
      'collected': 'ലഭിച്ചത്',
      'outstanding': 'ലഭിക്കാനുള്ളത്',

      'Bride': 'വധു',
      'Groom': 'വരൻ',
      'BizLedger': 'ബിസ് ലെഡ്ജർ',
      'PhotoLedger': 'ഫോട്ടോ ലെഡ്ജർ',
      'FoodLedger': 'ഫുഡ് ലെഡ്ജർ',
      'EventLedger': 'ഇവന്റ് ലെഡ്ജർ',
      'Ledger': 'ലെഡ്ജർ',
      'Wedding Studio': 'വെഡ്ഡിംഗ് സ്റ്റുഡിയോ',
      'Photography Studio': 'ഫോട്ടോഗ്രാഫി സ്റ്റുഡിയോ',
      'Catering Service': 'കാറ്ററിംഗ് സർവീസ്',
      'Event Planning': 'ഇവന്റ് പ്ലാനിംഗ്',
      'General Business': 'പൊതു ബിസിനസ്സ്',
      'Wedding Dates': 'വിവാഹ തീയതികൾ',
      'Session Dates': 'സെഷൻ തീയതികൾ',
      'Event Dates': 'ഇവന്റ് തീയതികൾ',
      'Service Dates': 'സേവന തീയതികൾ',
      'Wedding Date': 'വിവാഹ തീയതി',
      'Session Date': 'സെഷൻ തീയതി',
      'Event Date': 'ഇവന്റ് തീയതി',
      'Service Date': 'സേവന തീയതി',
      'Client': 'ക്ലയന്റ്',
      'Customer': 'ഉപഭോക്താവ്',
      'Client 1': 'ക്ലയന്റ് 1',
      'Client 2': 'ക്ലയന്റ് 2',
      'Contact': 'ബന്ധപ്പെടുക',
      'Contact 2': 'ബന്ധപ്പെടുക 2',
      'Wedding Report': 'വിവാഹ റിപ്പോർട്ട്',
      'Photography Report': 'ഫോട്ടോഗ്രാഫി റിപ്പോർട്ട്',
      'Catering Report': 'കാറ്ററിംഗ് റിപ്പോർട്ട്',
      'Event Report': 'ഇവന്റ് റിപ്പോർട്ട്',
      'General Report': 'പൊതു റിപ്പോർട്ട്',
      'No weddings booked yet. Add your first wedding!': 'വിവാഹങ്ങളൊന്നും ബുക്ക് ചെയ്തിട്ടില്ല. നിങ്ങളുടെ ആദ്യ വിവാഹം ചേർക്കുക!',
      'No sessions booked yet. Add your first session!': 'സെഷനുകളൊന്നും ബുക്ക് ചെയ്തിട്ടില്ല. നിങ്ങളുടെ ആദ്യ സെഷൻ ചേർക്കുക!',
      'No events booked yet. Add your first event!': 'ഇവന്റുകളൊന്നും ബുക്ക് ചെയ്തിട്ടില്ല. നിങ്ങളുടെ ആദ്യ ഇവന്റ് ചേർക്കുക!',
      'No records found. Add your first record!': 'രേഖകളൊന്നും കണ്ടെത്തിയില്ല. നിങ്ങളുടെ ആദ്യ റെക്കോർഡ് ചേർക്കുക!',

      'delete_bookings': 'ബുക്കിംഗുകൾ മായ്ക്കുക?',
      'cannot_undo': 'ഇത് തിരിച്ചെടുക്കാൻ കഴിയില്ല.',
      'cancel': 'റദ്ദാക്കുക',
      'share_text': 'വാചകം പങ്കിടുക (WhatsApp/മറ്റുള്ളവ)',
      'share_image_card': 'കാർഡ് ചിത്രം പങ്കിടുക',
      'change_to': 'മാറ്റുക',
      'change': 'മാറ്റുക',
      'business_changed': 'ബിസിനസ്സ് തരം മാറ്റി',
      'restore_backup': 'ബാക്കപ്പ് പുനഃസ്ഥാപിക്കണോ?',
      'import': 'ഇറക്കുമതി ചെയ്യുക',
      'enable': 'പ്രാപ്തമാക്കുക',
      'developer_options': 'ഡെവലപ്പർ ഓപ്ഷനുകൾ',
      'close': 'അടയ്ക്കുക',
      'contact_details': 'ബന്ധപ്പെടേണ്ട വിവരങ്ങൾ',
      'select_wedding_dates': 'തീയതികൾ തിരഞ്ഞെടുക്കുക',
      'internal_notes': 'ആന്തരിക കുറിപ്പുകൾ...',
      'advance_paid': 'മുൻകൂർ നൽകി',
      'pending': 'തീർപ്പുകൽപ്പിക്കാത്ത',
      'saved': 'സംരക്ഷിച്ചു!',
      'new_booking': 'പുതിയ ബുക്കിംഗ്',
      'edit_booking': 'ബുക്കിംഗ് തിരുത്തുക',
      'error': 'പിശക്',

      'app_locked': 'ആപ്പ് പൂട്ടിക്കിടക്കുന്നു',
      'authenticating': 'സ്ഥിരീകരിക്കുന്നു...',
      'unlock_continue': 'തുടരാൻ അൺലോക്ക് ചെയ്യുക',
      'tap_to_unlock': 'അൺലോക്ക് ചെയ്യാൻ സ്പർശിക്കുക',

      'help_create_title': 'ഒരു ബുക്കിംഗ് ഉണ്ടാക്കുക',
      'help_create_content': 'പുതിയ ബുക്കിംഗ് ഉണ്ടാക്കാൻ + ബട്ടൺ അമർത്തുക. ഉപഭോക്താവിന്റെ വിവരങ്ങൾ, തീയതികൾ എന്നിവ നൽകുക.',
      'help_create_step1': 'ഹോം സ്ക്രീനിലെ + ബട്ടൺ അമർത്തുക',
      'help_create_step2': 'ഉപഭോക്താവിന്റെ പേര് നൽകുക (നിർബന്ധം)',
      'help_create_step3': 'കലണ്ടർ ഉപയോഗിച്ച് തീയതി തിരഞ്ഞെടുക്കുക',
      'help_create_step4': 'സാമ്പത്തിക വിവരങ്ങൾ നൽകുക (തുക, അഡ്വാൻസ്)',
      'help_create_step5': 'സൂക്ഷിക്കാൻ DONE അമർത്തുക',
      'help_biz_title': 'ബിസിനസ്സ് തരം',
      'help_biz_content': 'BizLedger പല ബിസിനസ്സ് തരങ്ങളെ പിന്തുണയ്ക്കുന്നു. ഓരോ തരവും നിങ്ങളുടെ ബിസിനസ്സിനനുസരിച്ച് ആപ്പിനെ മാറ്റുന്നു.',
      'help_biz_step1': 'സെറ്റിങ്‌സിൽ പോയി ബിസിനസ്സ് തരം തിരഞ്ഞെടുക്കുക',
      'help_biz_step2': 'വെഡ്ഡിങ്, ഫോട്ടോഗ്രഫി തുടങ്ങി ആവശ്യമുള്ളത് തിരഞ്ഞെടുക്കുക',
      'help_biz_step3': 'സേവ് ചെയ്യുക',
      'help_calc_title': 'കണക്കുകൂട്ടലുകൾ',
      'help_calc_content': 'നികുതി, ഡിസ്കൗണ്ട് എന്നിവ ഉൾപ്പെടെയുള്ള വിശദമായ കണക്കുകൂട്ടലുകൾക്കൊപ്പം പണമിടപാടുകൾ ട്രാക്ക് ചെയ്യുക.',
      'help_calc_step1': 'മൊത്തം തുക നൽകുക',
      'help_calc_step2': 'ലഭിച്ച തുക നൽകുക',
      'help_calc_step3': 'ബാക്കി തുക ആപ്പ് തനിയെ കണക്കാക്കും',
      'help_share_title': 'കൈമാറലും റിപ്പോർട്ടുകളും',
      'help_share_content': 'ബുക്കിംഗുകൾ ചിത്രങ്ങളായോ PDF ആയോ അയക്കാം. സെറ്റിങ്‌സിൽ നിന്ന് ഇത് മാറ്റാം.',
      'help_share_step1': 'ബുക്കിംഗ് തുറക്കുക',
      'help_share_step2': 'ഷെയർ ഐക്കൺ അമർത്തുക',
      'help_share_step3': 'PDF അല്ലെങ്കിൽ ചിത്രം തിരഞ്ഞെടുക്കുക',
      'help_dark_title': 'ഡാർക്ക് മോഡ്',
      'help_dark_content': 'വെളിച്ചമുള്ളതും ഇരുണ്ടതുമായ തീമുകൾ മാറ്റാം.',
      'help_dark_step1': 'സെറ്റിങ്‌സിൽ പോകുക',
      'help_dark_step2': 'ഡാർക്ക് മോഡ് ഓൺ ചെയ്യുക',
      'help_backup_title': 'ബാക്കപ്പും റീസ്റ്റോറും',
      'help_backup_content': 'നിങ്ങളുടെ വിവരങ്ങൾ ഫോണിലോ ഗൂഗിൾ ഡ്രൈവിലോ സുരക്ഷിതമായി ബാക്കപ്പ് ചെയ്യുക.',
      'help_backup_step1': 'സെറ്റിംഗ്സ് > ബാക്കപ്പ് & സിങ്ക് തുറക്കുക',
      'help_backup_step2': 'ഫയൽ ഫോണിലേക്ക് മാറ്റാൻ "ബാക്കപ്പ് എക്സ്പോർട്ട് ചെയ്യുക" അമർത്തുക.',
      'help_backup_step3': 'ഗൂഗിൾ ഡ്രൈവിലേക്ക് മാറ്റാൻ "ബാക്കപ്പ് ടു ഡ്രൈവ്" അമർത്തുക.',
      'help_backup_step4': 'റീസ്റ്റോർ ചെയ്യാൻ "ഇമ്പോർട്ട് ചെയ്യുക" അല്ലെങ്കിൽ "റീസ്റ്റോർ ഫ്രം ഡ്രൈവ്" അമർത്തുക.',
      'vownote': 'BizLedger',
      'search': 'ബുക്കിംഗുകൾ തിരയുക...',
      'no_bookings': 'ബുക്കിംഗുകൾ ലഭ്യമല്ല',
      'completed': 'പൂർത്തിയായി',
      'address': 'വിലാസം',
      'phone': 'ഫോൺ',
      'dates': 'തിയതികൾ',
      'total': 'ആകെ തുക',
      'received': 'ആകെ ലഭിച്ചത്',
      'due': 'അവസാന ബാക്കി',
      'done': 'പൂർത്തിയായി',
      'delete': 'ഡിലീറ്റ്',
      'export_pdf': 'പ്രതിമാസ PDF',
      'customer': 'കസ്റ്റമർ',
      'settings': 'സെറ്റിംഗ്സ്',
      'language': 'ഭാഷ',
      'money_in_pdf': 'PDF-ൽ തുക കാണിക്കുക',
      'help_center': 'ഹെൽപ് സെന്റർ',
      'help_text': 'BizLedger എങ്ങനെ പ്രൊഫഷണലായി ഉപയോഗിക്കാം എന്ന് മനസ്സിലാക്കുക. നിങ്ങളുടെ വിവാഹ ബുക്കിംഗുകൾ ട്രാക്ക് ചെയ്യാനും അഡ്വാൻസ് മാനേജ് ചെയ്യാനും സ്റ്റുഡിയോ റിപ്പോർട്ടുകൾ തയ്യാറാക്കാനും ഇത് സഹായിക്കുന്നു.',
      'bride': 'വധുവിന്റെ പേര്',
      'groom': 'വരന്റെ പേര്',
      'alt_phone': 'മറ്റൊരു ഫോൺ നമ്പർ',
      'notes': 'പ്രത്യേക കുറിപ്പുകൾ',
      'total_adv': 'ആകെ അഡ്വാൻസ്',
      'adv_received': 'ലഭിച്ച അഡ്വാൻസ്',
      'adv_pending': 'അഡ്വാൻസ് ബാക്കി',
      'diary_mgmt': 'ഡയറി മാനേജ്‌മെന്റ്',
      'category': 'ബുക്കിംഗ് വിഭാഗം',
      'male': 'പുരുഷൻ',
      'female': 'സ്ത്രീ',
      'diary_code': 'ഡയറി കോഡ്',
      'diary_ref': 'ഡയറി റെഫ്',
      'save_booking': 'ബുക്കിംഗ് സേവ് ചെയ്യുക',
      'export_settings': 'എക്സ്പോർട്ട് സെറ്റിംഗ്സ്',
      'show_names': 'പേരുകൾ എക്സ്പോർട്ടിൽ കാണിക്കുക',
      'show_phone': 'ഫോൺ നമ്പർ എക്സ്പോർട്ടിൽ കാണിക്കുക',
      'show_address': 'വിലാസം എക്സ്പോർട്ടിൽ കാണിക്കുക',
      'show_diary': 'ഡയറി റെഫ് എക്സ്പോർട്ടിൽ കാണിക്കുക',
      'screenshot_4k': 'പ്രൊഫഷണൽ 4K സ്നാപ്പ്ഷോട്ടുകൾ',
      'share_image': 'ചിത്രമായി പങ്കിടുക',
      'full_report': 'പൂർണ്ണ റിപ്പോർട്ട് എടുക്കുക',
      'generating_pdf': 'പ്രൊഫഷണൽ PDF തയ്യാറാക്കുന്നു...',
      'app': 'ആപ്പ്',
    },
    'hi': {
      'Wedding Studio': 'वेडिंग स्टूडियो',
      'Photography Studio': 'फोटोग्राफी स्टूडियो',
      'Catering Service': 'केटरिंग सर्विस',
      'Event Planning': 'इवेंट प्लानिंग',
      'General Business': 'सामान्य व्यवसाय',
      'Wedding Report': 'वेडिंग रिपोर्ट',
      'Photography Report': 'फोटोग्राफी रिपोर्ट',
      'Catering Report': 'केटरिंग रिपोर्ट',
      'Event Report': 'इवेंट रिपोर्ट',
      'Business Report': 'व्यवसाय रिपोर्ट',
      'Wedding Dates': 'शादी की तारीखें',
      'Session Dates': 'सत्र की तारीखें',
      'Service Dates': 'सेवा की तारीखें',
      'Event Dates': 'इवेंट की तारीखें',
      'Wedding Date': 'शादी की तारीख',
      'Session Date': 'सत्र की तारीख',
      'Service Date': 'सेवा की तारीख',
      'Event Date': 'इवेंट की तारीख',
      'Partner Name': 'साझेदार का नाम',
      'Contact Person': 'सम्पर्क व्यक्ति',
      'Secondary Contact': 'द्वितीयक सम्पर्क',
      'Organizer': 'आयोजक',
      'Co-Organizer': 'सह-आयोजक',
      'No weddings booked yet.\nTap + to create your first booking.': 'अभी तक कोई शादी बुक नहीं हुई है।\nअपनी पहली बुकिंग बनाने के लिए + टैप करें।',
      'No photoshoots booked yet.\nTap + to schedule your first session.': 'अभी तक कोई फोटोशूट बुक नहीं हुआ है।\nअपना पहला सत्र शेड्यूल करने के लिए + टैप करें।',
      'No catering orders yet.\nTap + to add your first booking.': 'अभी तक कोई केटरिंग ऑर्डर नहीं है।\nअपनी पहली बुकिंग जोड़ने के लिए + टैप करें।',
      'No events planned yet.\nTap + to create your first event.': 'अभी तक कोई इवेंट प्लान नहीं हुआ है।\nअपना पहला इवेंट बनाने के लिए + टैप करें।',
      'No bookings yet.\nTap + to create your first booking.': 'अभी तक कोई बुकिंग नहीं है।\nअपनी पहली बुकिंग बनाने के लिए + टैप करें।',
      'add_date': 'तारीख जोड़ें',
      'required': 'आवश्यक',
      'gdrive_sync': 'गूगल ड्राइव सिंक',
      'gdrive_desc': 'अपने व्यक्तिगत गूगल ड्राइव (AppData) पर सुरक्षित रूप से बैकअप लें',
      'sign_in_google': 'गूगल के साथ साइन इन करें',
      'sign_out': 'साइन आउट',
      'backup_to_drive': 'ड्राइव में बैकअप लें',
      'restore_from_drive': 'ड्राइव से रीस्टोर करें',
      'connected_as': 'कनेक्टेड हैं',
      'backup_success': 'बैकअप सफलतापूर्वक अपलोड किया गया!',
      'restore_success': 'पुनर्प्राप्ति पूरी हुई! कृपया ऐप रीस्टार्ट करें।',
      'error_backup': 'बैकअप विफल रहा',
      'error_restore': 'रीस्टोर विफल रहा',
      'business_type': 'व्यवसाय प्रकार',

      'delete_booking_q': 'बुकिंग हटाएं?',
      'no_image_card': 'कोई छवि कार्ड नहीं',
      'due': 'बकाया',
      'paid': 'भुगतान किया गया',
      'booking_confirmed_title': 'बुकिंग की पुष्टि हो गई',
      'not_applicable': 'लागू नहीं',
      'address': 'पता',
      'contact': 'संपर्क',
      'financials': 'वित्तीय जानकारी',
      'total': 'कुल',
      'received': 'प्राप्त',
      'thank_you': 'धन्यवाद',
      'selected': 'चयनित',
      'auth_reason': 'ऐप एक्सेस करने के लिए प्रमाणित करें',
      'face_id': 'फेस आईडी',
      'fingerprint': 'फिंगरप्रिंट',
      'iris': 'आइरिस',
      'biometric': 'बायोमेट्रिक',

      'select_business_type': 'व्यवसाय का प्रकार चुनें',
      'BUSINESS': 'व्यवसाय',
      'APPEARANCE': 'दिखावट',
      'dark_mode': 'डार्क मोड',
      'ABOUT': 'विवरण',
      'version': 'संस्करण',
      'privacy_policy': 'गोपनीयता नीति',
      'licenses': 'लाइसेंस',
      'github': 'GitHub',
      'EXPORT': 'निर्यात',
      'manage_pdf_layout': 'PDF लेआउट और गुणवत्ता प्रबंधित करें',
      'SECURITY': 'सुरक्षा',
      'app_lock_biometrics': 'ऐप लॉक (बायोमेट्रिक्स)',
      'enable_biometric': 'फिंगरप्रिंट या फेस अनलॉक सक्षम करें',
      'biometrics_unavailable': 'इस डिवाइस पर बायोमेट्रिक्स उपलब्ध नहीं है',
      'BACKUP & SYNC': 'बैकअप और सिंक',
      'export_backup': 'बैकअप निर्यात करें',
      'import_backup': 'बैकअप आयात करें',
      'auto_backup': 'ऑटो बैकअप',
      'import_backup_warning': 'यह बुकिंग को वर्तमान सूची के साथ मिला देगा।',
      'HELP': 'सहायता',
      'fps_monitor': 'FPS मॉनिटर',
      'promotion_120hz': 'प्रोमोशन (120Hz)',
      'saved_successfully': 'सफलतापूर्वक सहेजा गया',
      'customer_information': 'ग्राहक की जानकारी',
      'finance_details': 'वित्तीय विवरण',
      'business_insights': 'व्यवसाय अंतर्दृष्टि',
      'monthly_performance': 'मासिक प्रदर्शन',
      'total_valuation': 'कुल मूल्यांकन',
      'events_count': 'आयोजन',
      'collected': 'प्राप्त',
      'outstanding': 'बकाया',

      'Bride': 'दुल्हन',
      'Groom': 'दूल्हा',
      'BizLedger': 'बिज़ लेजर',
      'PhotoLedger': 'फोटो लेजर',
      'FoodLedger': 'फ़ूड लेजर',
      'EventLedger': 'इवेंट लेजर',
      'Ledger': 'लेजर',
      'Wedding Studio': 'वेडिंग स्टूडियो',
      'Photography Studio': 'फोटोग्राफी स्टूडियो',
      'Catering Service': 'कैटरिंग सेवा',
      'Event Planning': 'इवेंट प्लानिंग',
      'General Business': 'सामान्य व्यापार',
      'Wedding Dates': 'शादी की तारीखें',
      'Session Dates': 'सत्र की तारीखें',
      'Event Dates': 'इवेंट की तारीखें',
      'Service Dates': 'सेवा की तारीखें',
      'Wedding Date': 'शादी की तारीख',
      'Session Date': 'सत्र की तारीख',
      'Event Date': 'इवेंट की तारीख',
      'Service Date': 'सेवा की तारीख',
      'Client': 'क्लाइंट',
      'Customer': 'ग्राहक',
      'Client 1': 'क्लाइंट 1',
      'Client 2': 'क्लाइंट 2',
      'Contact': 'संपर्क',
      'Contact 2': 'संपर्क 2',
      'Wedding Report': 'शादी की रिपोर्ट',
      'Photography Report': 'फोटोग्राफी रिपोर्ट',
      'Catering Report': 'कैटरिंग रिपोर्ट',
      'Event Report': 'इवेंट रिपोर्ट',
      'General Report': 'सामान्य रिपोर्ट',
      'No weddings booked yet. Add your first wedding!': 'अभी तक कोई शादी बुक नहीं हुई है। अपनी पहली शादी जोड़ें!',
      'No sessions booked yet. Add your first session!': 'अभी तक कोई सत्र बुक नहीं हुआ है। अपना पहला सत्र जोड़ें!',
      'No events booked yet. Add your first event!': 'अभी तक कोई इवेंट बुक नहीं हुआ है। अपना पहला इवेंट जोड़ें!',
      'No records found. Add your first record!': 'कोई रिकॉर्ड नहीं मिला। अपना पहला रिकॉर्ड जोड़ें!',

      'delete_bookings': 'बुकिंग हटाएं?',
      'cannot_undo': 'इस कार्रवाई को पूर्ववत नहीं किया जा सकता।',
      'cancel': 'रद्द करें',
      'share_text': 'टेक्स्ट साझा करें (WhatsApp/अन्य)',
      'share_image_card': 'कार्ड छवि साझा करें',
      'change_to': 'में बदलें',
      'change': 'बदलें',
      'business_changed': 'व्यवसाय का प्रकार बदल गया',
      'restore_backup': 'बैकअप पुनर्स्थापित करें?',
      'import': 'आयात करें',
      'enable': 'सक्षम करें',
      'developer_options': 'डेवलपर विकल्प',
      'close': 'बंद करें',
      'contact_details': 'संपर्क विवरण',
      'select_wedding_dates': 'कृपया तिथियों का चयन करें',
      'internal_notes': 'आंतरिक नोट्स...',
      'advance_paid': 'अग्रिम भुगतान किया',
      'pending': 'लंबित',
      'saved': 'सहेजा गया!',
      'new_booking': 'नई बुकिंग',
      'edit_booking': 'बुकिंग संपादित करें',
      'error': 'त्रुटि',

      'app_locked': 'ऐप लॉक है',
      'authenticating': 'प्रमाणीकरण हो रहा है...',
      'unlock_continue': 'जारी रखने के लिए अनलॉक करें',
      'tap_to_unlock': 'अनलॉक करने के लिए टैप करें',

      'help_create_title': 'बुकिंग बनाना',
      'help_create_content': 'नया बुकिंग बनाने के लिए + बटन पर टैप करें।',
      'help_create_step1': 'होम स्क्रीन पर फ़्लोटिंग + बटन पर टैप करें',
      'help_create_step2': 'ग्राहक का नाम दर्ज करें (आवश्यक)',
      'help_create_step3': 'कैलेंडर का उपयोग करके ईवेंट की तिथियाँ चुनें',
      'help_create_step4': 'वित्तीय विवरण जोड़ें (कुल, अग्रिम, भुगतान)',
      'help_create_step5': 'सहेजने के लिए DONE पर टैप करें',
      'help_biz_title': 'व्यवसाय के प्रकार',
      'help_biz_content': 'BizLedger कई व्यावसायिक प्रकारों का समर्थन करता है।',
      'help_biz_step1': 'सेटिंग्स → व्यवसाय प्रकार पर जाएँ',
      'help_biz_step2': 'विवाह, फ़ोटोग्राफ़ी, खानपान, ईवेंट या सामान्य में से चुनें',
      'help_biz_step3': 'अपने चयन की पुष्टि करें',
      'help_calc_title': 'उन्नत गणनाएँ',
      'help_calc_content': 'कर, छूट और कई भुगतान विधियों सहित विस्तृत गणनाओं के साथ भुगतानों को ट्रैक करें।',
      'help_calc_step1': 'बुकिंग फॉर्म में कुल राशि जोड़ें',
      'help_calc_step2': 'अग्रिम और प्राप्त राशि जोड़ें',
      'help_calc_step3': 'ऐप स्वतः लंबित की गणना करता है',
      'help_share_title': 'साझा करना और निर्यात करना',
      'help_share_content': 'बुकिंग को छवि या पीडीएफ के रूप में निर्यात करें।',
      'help_share_step1': 'कोई भी बुकिंग खोलें',
      'help_share_step2': 'शेयर आइकन पर टैप करें',
      'help_share_step3': 'निर्यात प्रारूप चुनें',
      'help_dark_title': 'डार्क मोड',
      'help_dark_content': 'अनुकूलित एनिमेशन के साथ लाइट और डार्क थीम के बीच स्विच करें।',
      'help_dark_step1': 'सेटिंग्स पर जाएँ',
      'help_dark_step2': '"डार्क मोड" चालू या बंद करें',
      'help_backup_title': 'बैकअप और पुनर्स्थापना',
      'help_backup_content': 'अपनी बुकिंग को सुरक्षित रूप से स्थानीय रूप से बैकअप लें या Google Drive पर सिंक करें।',
      'help_backup_step1': 'सेटिंग्स > बैकअप और सिंक पर जाएं',
      'help_backup_step2': 'डेटा सहेजने के लिए "बैकअप निर्यात करें" पर टैप करें।',
      'help_backup_step3': 'क्लाउड में सुरक्षित डेटा अपलोड करने के लिए "ड्राइव में बैकअप लें" पर टैप करें।',
      'help_backup_step4': 'पुनर्स्थापित करने के लिए "आयात करें" या "ड्राइव से पुनर्स्थापित करें" पर टैप करें।',
      'vownote': 'BizLedger',
      'search': 'खोजें...',
      'no_bookings': 'कोई बुकिंग नहीं मिली',
      'completed': 'पूरा हुआ',
      'address': 'पता',
      'phone': 'फ़ोन',
      'dates': 'तिथियाँ',
      'total': 'कुल राशि',
      'received': 'कुल प्राप्त',
      'due': 'अंतिम शेष',
      'done': 'संपन्न',
      'delete': 'हटाएं',
      'export_pdf': 'मासिक पीडीएफ निर्यात करें',
      'customer': 'ग्राहक',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'money_in_pdf': 'पीडीएफ में पैसा दिखाएं',
      'help_center': 'सहायता केंद्र',
      'help_text': 'BizLedger का उपयोग करना सीखें।',
      'bride': 'दुल्हन का नाम',
      'groom': 'दूल्हे का नाम',
      'alt_phone': 'वैकल्पिक फ़ोन',
      'notes': 'विशेष नोट',
      'total_adv': 'कुल अग्रिम',
      'adv_received': 'अग्रिम प्राप्त',
      'adv_pending': 'अग्रिम लंबित',
      'diary_mgmt': 'डायरी प्रबंधन',
      'category': 'बुकिंग का प्रकार',
      'male': 'पुरुष',
      'female': 'महिला',
      'diary_code': 'डायरी कोड',
      'diary_ref': 'डायरी संदर्भ',
      'save_booking': 'बुकिंग सहेजें',
      'export_settings': 'निर्यात सेटिंग्स',
      'show_names': 'नाम दिखाएं',
      'show_phone': 'फ़ोन दिखाएं',
      'show_address': 'पता दिखाएं',
      'show_diary': 'डायरी संदर्भ दिखाएं',
      'screenshot_4k': '4K स्क्रीनशॉट',
      'share_image': 'छवि के रूप में साझा करें',
      'full_report': 'पूर्ण रिपोर्ट बनाएं',
      'generating_pdf': 'पीडीएफ जनरेट हो रहा है...',
      'app': 'ऐप',
    },
    'ta': {
      'delete_booking_q': 'முன்பதிவை நீக்கவா?',
      'no_image_card': 'படம் கார்டு இல்லை',
      'due': 'நிலுவை',
      'paid': 'செலுத்தப்பட்டது',
      'booking_confirmed_title': 'முன்பதிவு உறுதி செய்யப்பட்டது',
      'not_applicable': 'பொருந்தாது',
      'address': 'முகவரி',
      'contact': 'தொடர்பு',
      'financials': 'நிதித் தகவல்கள்',
      'total': 'மொத்தம்',
      'received': 'பெறப்பட்டது',
      'thank_you': 'நன்றி',
      'selected': 'தேர்ந்தெடுக்கப்பட்டது',
      'auth_reason': 'பயன்பாட்டை அணுக அங்கீகரிக்கவும்',
      'face_id': 'ஃபேஸ் ஐடி',
      'fingerprint': 'கைரேகை',
      'iris': 'ஐரிஸ்',
      'biometric': 'பயோமெட்ரிக்',

      'select_business_type': 'வணிக வகையைத் தேர்ந்தெடுக்கவும்',
      'BUSINESS': 'வணிகம்',
      'APPEARANCE': 'தோற்றம்',
      'dark_mode': 'டார்க் மோட்',
      'ABOUT': 'விவரங்கள்',
      'version': 'பதிப்பு',
      'privacy_policy': 'தனியுரிமைக் கொள்கை',
      'licenses': 'உரிமங்கள்',
      'github': 'GitHub',
      'EXPORT': 'ஏற்றுமதி',
      'manage_pdf_layout': 'PDF தளவமைப்பு & தரத்தை நிர்வகி',
      'SECURITY': 'பாதுகாப்பு',
      'app_lock_biometrics': 'ஆப் லாக் (பயோமெட்ரிக்ஸ்)',
      'enable_biometric': 'கைரேகை அல்லது முக அன்லாக்கை இயக்கு',
      'biometrics_unavailable': 'இந்த சாதனத்தில் பயோமெட்ரிக்ஸ் கிடைக்கவில்லை',
      'BACKUP & SYNC': 'காப்புப்பிரதி & ஒத்திசைவு',
      'export_backup': 'காப்புப்பிரதி ஏற்றுமதி',
      'import_backup': 'காப்புப்பிரதி இறக்குமதி',
      'auto_backup': 'தானியங்கி காப்புப்பிரதி',
      'import_backup_warning': 'இது தற்போதைய பட்டியலுடன் முன்பதிவுகளை இணைக்கும்.',
      'HELP': 'உதவி',
      'fps_monitor': 'FPS மானிட்டர்',
      'promotion_120hz': 'புரோமோஷன் (120Hz)',
      'saved_successfully': 'வெற்றிகரமாக சேமிக்கப்பட்டது',
      'customer_information': 'வாடிக்கையாளர் தகவல்',
      'finance_details': 'நிதி விவரங்கள்',
      'business_insights': 'வணிக நுண்ணறிவு',
      'monthly_performance': 'மாதாந்திர செயல்திறன்',
      'total_valuation': 'மொத்த மதிப்பு',
      'events_count': 'நிகழ்வுகள்',
      'collected': 'பெறப்பட்டது',
      'outstanding': 'நிலுவையில் உள்ளவை',

      'delete_bookings': 'பதிவுகளை நீக்கவா?',
      'cannot_undo': 'இதை மீட்டெடுக்க முடியாது.',
      'cancel': 'ரத்துசெய்',
      'share_text': 'உரையைப் பகிரவும் (WhatsApp/மற்றவை)',
      'share_image_card': 'படம் பகிரவும்',
      'change_to': 'மாற்று',
      'change': 'மாற்று',
      'business_changed': 'வணிக வகை மாற்றப்பட்டது',
      'restore_backup': 'காப்புப் பிரதி மீட்டமைக்கவா?',
      'import': 'இறக்குமதி செய்',
      'enable': 'செயல்படுத்து',
      'developer_options': 'டெவலப்பர் விருப்பங்கள்',
      'close': 'மூடு',
      'contact_details': 'தொடர்பு விவரங்கள்',
      'select_wedding_dates': 'தேதிகளைத் தேர்ந்தெடுக்கவும்',
      'internal_notes': 'உள் குறிப்புகள்...',
      'advance_paid': 'முன்பணம்',
      'pending': 'நிலுவையில்',
      'saved': 'சேமிக்கப்பட்டது!',
      'new_booking': 'புதிய பதிவு',
      'edit_booking': 'பதிவைத் திருத்து',
      'error': 'பிழை',

      'app_locked': 'பயன்பாடு பூட்டப்பட்டுள்ளது',
      'authenticating': 'சரிபார்க்கிறது...',
      'unlock_continue': 'தொடர திறக்கவும்',
      'tap_to_unlock': 'திறக்க தட்டவும்',

      'help_create_title': 'புதிய முன்பதிவு',
      'help_create_content': 'புதிய முன்பதிவை உருவாக்க + பட்டனை அழுத்தவும். வாடிக்கையாளர் விவரங்கள் மற்றும் தேதிகளை உள்ளிடவும்.',
      'help_create_step1': '+ பட்டனை அழுத்தவும்',
      'help_create_step2': 'பெயரை உள்ளிடவும்',
      'help_create_step3': 'தேதிகளை தேர்ந்தெடுக்கவும்',
      'help_create_step4': 'நிதி விவரங்களை சேர்க்கவும்',
      'help_create_step5': 'DONE என்பதை அழுத்தவும்',
      'help_biz_title': 'வணிக வகைகள்',
      'help_biz_content': 'BizLedger பல வணிக வகைகளை ஆதரிக்கிறது.',
      'help_biz_step1': 'அமைப்புகளுக்கு செல்லவும்',
      'help_biz_step2': 'வகையை தேர்ந்தெடுக்கவும்',
      'help_biz_step3': 'உறுதிப்படுத்தவும்',
      'help_calc_title': 'கணக்கீடுகள்',
      'help_calc_content': 'வரி மற்றும் தள்ளுபடியுடன் भुகதాలను கண்कாணிக்கவும்.',
      'help_calc_step1': 'மொத்த தொகையை சேர்க்கவும்',
      'help_calc_step2': 'முன்பணத்தை சேர்க்கவும்',
      'help_calc_step3': 'மீதத்தை கணக்கிடும்',
      'help_share_title': 'பகிர்தல்',
      'help_share_content': 'படமாக அல்லது PDF ஆக பகிரவும்.',
      'help_share_step1': 'முன்பதிவை திறக்கவும்',
      'help_share_step2': 'பகிர்வு ஐகானை அழுத்தவும்',
      'help_share_step3': 'வடிவத்தை தேர்ந்தெடுக்கவும்',
      'help_dark_title': 'டார்க் மோட்',
      'help_dark_content': 'தீம்களை மாற்றவும்.',
      'help_dark_step1': 'அமைப்புகளுக்கு செல்லவும்',
      'help_dark_step2': 'டார்க் மோடை மாற்றவும்',
      'help_backup_title': 'காப்புப்பிரதி & மீட்பு',
      'help_backup_content': 'உங்கள் தகவலை உள்நாட்டில் காப்புப்பிரதி எடுக்கவும் அல்லது Google இயக்ககத்தில் ஒத்திசைக்கவும்.',
      'help_backup_step1': 'அமைப்புகள் > காப்புப்பிரதி & ஒத்திசைவுக்குச் செல்லவும்',
      'help_backup_step2': '"காப்புப்பிரதியை ஏற்றுமதி செய்" என்பதைத் தட்டவும்.',
      'help_backup_step3': '"இயக்ககத்தில் காப்புப்பிரதி" என்பதைத் தட்டவும்.',
      'help_backup_step4': '"இறக்குமதி செய்" அல்லது "இயக்ககத்திலிருந்து மீட்டமை" என்பதைத் தட்டவும்.',
      'vownote': 'BizLedger',
      'search': 'தேடு...',
      'no_bookings': 'முன்பதிவுகள் இல்லை',
      'completed': 'முடிந்தது',
      'address': 'முகவரி',
      'phone': 'தொலைபேசி',
      'dates': 'தேதிகள்',
      'total': 'மொத்த தொகை',
      'received': 'பெறப்பட்டது',
      'due': 'நிலுவை',
      'done': 'முடிந்தது',
      'delete': 'நீக்கு',
      'export_pdf': 'PDF ஏற்றுமதி',
      'customer': 'வாடிக்கையாளர்',
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'money_in_pdf': 'PDF-ல் தொகையை காட்டு',
      'help_center': 'உதவி மையம்',
      'help_text': 'BizLedger-ஐ எவ்வாறு பயன்படுத்துவது என்று கற்றுக்கொள்ளுங்கள்.',
      'bride': 'மணமகள் பெயர்',
      'groom': 'மணமகன் பெயர்',
      'alt_phone': 'மாற்று தொலைபேசி',
      'notes': 'குறிப்புகள்',
      'total_adv': 'மொத்த முன்பணம்',
      'adv_received': 'பெற்ற முன்பணம்',
      'adv_pending': 'மீதமுள்ள முன்பணம்',
      'diary_mgmt': 'டைரி மேலாண்மை',
      'category': 'முன்பதிவு வகை',
      'male': 'ஆண்',
      'female': 'பெண்',
      'diary_code': 'டைரி குறியீடு',
      'diary_ref': 'டைரி குறிப்பு',
      'save_booking': 'முன்பதிவை சேமி',
      'export_settings': 'ஏற்றுமதி அமைப்புகள்',
      'show_names': 'பெயர்களைக் காட்டு',
      'show_phone': 'தொலைபேசியைக் காட்டு',
      'show_address': 'முகவரியைக் காட்டு',
      'show_diary': 'டைரி குறிப்பைக் காட்டு',
      'screenshot_4k': '4K புகைப்படம்',
      'share_image': 'படமாக பகிர்',
      'full_report': 'முழு அறிக்கையை உருவாக்கு',
      'generating_pdf': 'PDF உருவாக்கப்படுகிறது...',
      'app': 'பயன்பாடு',
    },
    'es': {
      'delete_booking_q': '¿Eliminar reserva?',
      'no_image_card': 'SIN TARJETA DE IMAGEN',
      'due': 'Pendiente',
      'paid': 'Pagado',
      'booking_confirmed_title': 'Reserva confirmada',
      'not_applicable': 'N/A',
      'address': 'Dirección',
      'contact': 'Contacto',
      'financials': 'Datos financieros',
      'total': 'Total',
      'received': 'Recibido',
      'thank_you': '¡Gracias!',
      'selected': 'Seleccionado',
      'auth_reason': 'Autentíquese para acceder a la aplicación',
      'face_id': 'Face ID',
      'fingerprint': 'Huella dactilar',
      'iris': 'Iris',
      'biometric': 'Biométrico',

      'select_business_type': 'Seleccionar tipo de negocio',
      'BUSINESS': 'NEGOCIO',
      'APPEARANCE': 'APARIENCIA',
      'dark_mode': 'Modo oscuro',
      'ABOUT': 'ACERCA DE',
      'version': 'Versión',
      'privacy_policy': 'Política de privacidad',
      'licenses': 'Licencias',
      'github': 'GitHub',
      'EXPORT': 'EXPORTAR',
      'manage_pdf_layout': 'Gestionar diseño y calidad de PDF',
      'SECURITY': 'SEGURIDAD',
      'app_lock_biometrics': 'Bloqueo de aplicación (Biometría)',
      'enable_biometric': 'Habilitar huella dactilar o desbloqueo facial',
      'biometrics_unavailable': 'Biometría no disponible en este dispositivo',
      'BACKUP & SYNC': 'COPIA DE SEGURIDAD Y SINCRONIZACIÓN',
      'export_backup': 'Exportar copia de seguridad',
      'import_backup': 'Importar copia de seguridad',
      'auto_backup': 'Copia de seguridad automática',
      'import_backup_warning': 'Esto fusionará las reservas con la lista actual.',
      'HELP': 'AYUDA',
      'fps_monitor': 'Monitor FPS',
      'promotion_120hz': 'ProMotion (120Hz)',
      'saved_successfully': 'Guardado exitosamente',
      'customer_information': 'Información del cliente',
      'finance_details': 'Detalles financieros',
      'business_insights': 'Información comercial',
      'monthly_performance': 'Rendimiento mensual',
      'total_valuation': 'VALORACIÓN TOTAL',
      'events_count': 'Eventos',
      'collected': 'Cobrado',
      'outstanding': 'Pendiente',

      'Bride': 'Novia',
      'Groom': 'Novio',
      'BizLedger': 'BizLedger',
      'PhotoLedger': 'PhotoLedger',
      'FoodLedger': 'FoodLedger',
      'EventLedger': 'EventLedger',
      'Ledger': 'Ledger',
      'Wedding Studio': 'Estudio de Bodas',
      'Photography Studio': 'Estudio de Fotografía',
      'Catering Service': 'Servicio de Catering',
      'Event Planning': 'Planificación de Eventos',
      'General Business': 'Negocio General',
      'Wedding Dates': 'Fechas de Boda',
      'Session Dates': 'Fechas de Sesión',
      'Event Dates': 'Fechas de Eventos',
      'Service Dates': 'Fechas de Servicio',
      'Wedding Date': 'Fecha de Boda',
      'Session Date': 'Fecha de Sesión',
      'Event Date': 'Fecha de Evento',
      'Service Date': 'Fecha de Servicio',
      'Client': 'Cliente',
      'Customer': 'Cliente',
      'Client 1': 'Cliente 1',
      'Client 2': 'Cliente 2',
      'Contact': 'Contacto',
      'Contact 2': 'Contacto 2',
      'Wedding Report': 'Reporte de Boda',
      'Photography Report': 'Reporte de Fotografía',
      'Catering Report': 'Reporte de Catering',
      'Event Report': 'Reporte de Eventos',
      'General Report': 'Reporte General',
      'No weddings booked yet. Add your first wedding!': 'Aún no se han reservado bodas. ¡Agrega tu primera boda!',
      'No sessions booked yet. Add your first session!': 'Aún no se han reservado sesiones. ¡Agrega tu primera sesión!',
      'No events booked yet. Add your first event!': 'Aún no se han reservado eventos. ¡Agrega tu primer evento!',
      'No records found. Add your first record!': 'No se encontraron registros. ¡Agrega tu primer registro!',

      'delete_bookings': '¿Eliminar reservas?',
      'cannot_undo': 'Esta acción no se puede deshacer.',
      'cancel': 'Cancelar',
      'share_text': 'Compartir texto (WhatsApp/Otros)',
      'share_image_card': 'Compartir imagen de tarjeta',
      'change_to': 'Cambiar a',
      'change': 'Cambiar',
      'business_changed': 'Tipo de negocio cambiado a',
      'restore_backup': '¿Restaurar copia de seguridad?',
      'import': 'Importar',
      'enable': 'Habilitar',
      'developer_options': 'Opciones de desarrollador',
      'close': 'Cerrar',
      'contact_details': 'Detalles de contacto',
      'select_wedding_dates': 'Seleccione las fechas',
      'internal_notes': 'Notas internas...',
      'advance_paid': 'Anticipo Pagado',
      'pending': 'Pendiente',
      'saved': '¡Guardado!',
      'new_booking': 'Nueva Reserva',
      'edit_booking': 'Editar Reserva',
      'error': 'Error',

      'app_locked': 'App Bloqueada',
      'authenticating': 'Autenticando...',
      'unlock_continue': 'Desbloquear para continuar',
      'tap_to_unlock': 'Toca para desbloquear con',

      'help_create_title': 'Crear una Reserva',
      'help_create_content': 'Toque el botón + para crear una reserva.',
      'help_create_step1': 'Toque el botón +',
      'help_create_step2': 'Ingrese el nombre',
      'help_create_step3': 'Seleccione fechas',
      'help_create_step4': 'Agregue finanzas',
      'help_create_step5': 'Toque HECHO',
      'help_biz_title': 'Tipos de Negocio',
      'help_biz_content': 'Soporta múltiples tipos de negocio.',
      'help_biz_step1': 'Ajustes',
      'help_biz_step2': 'Elija el tipo',
      'help_biz_step3': 'Confirme',
      'help_calc_title': 'Cálculos',
      'help_calc_content': 'Rastree pagos con impuestos.',
      'help_calc_step1': 'Agregue el total',
      'help_calc_step2': 'Agregue el anticipo',
      'help_calc_step3': 'Calcula saldo',
      'help_share_title': 'Compartir',
      'help_share_content': 'Exporte reservas como PDF.',
      'help_share_step1': 'Abra una reserva',
      'help_share_step2': 'Toque compartir',
      'help_share_step3': 'Elija formato',
      'help_dark_title': 'Modo Oscuro',
      'help_dark_content': 'Cambie temas.',
      'help_dark_step1': 'Ajustes',
      'help_dark_step2': 'Active Modo Oscuro',
      'help_backup_title': 'Copia de Seguridad',
      'help_backup_content': 'Cree copias de seguridad locales o sincronícelas con Google Drive.',
      'help_backup_step1': 'Vaya a Ajustes > Copia de Seguridad',
      'help_backup_step2': 'Toque "Exportar copia" para guardar datos en la carpeta Documentos.',
      'help_backup_step3': 'Toque "Copia en Drive" para subir y proteger sus datos en la nube.',
      'help_backup_step4': 'Para restaurar, toque "Importar" o "Restaurar desde Drive".',
      'vownote': 'BizLedger',
      'search': 'Buscar...',
      'no_bookings': 'No hay reservas',
      'completed': 'Completado',
      'address': 'Dirección',
      'phone': 'Teléfono',
      'dates': 'Fechas',
      'total': 'Total',
      'received': 'Recibido',
      'due': 'Saldo',
      'done': 'Hecho',
      'delete': 'Eliminar',
      'export_pdf': 'Exportar PDF',
      'customer': 'Cliente',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'money_in_pdf': 'Mostrar Dinero en PDF',
      'help_center': 'Centro de Ayuda',
      'help_text': 'Aprende a usar BizLedger.',
      'bride': 'Novia',
      'groom': 'Novio',
      'alt_phone': 'Teléfono Alt',
      'notes': 'Notas',
      'total_adv': 'Anticipo Total',
      'adv_received': 'Anticipo Recibido',
      'adv_pending': 'Anticipo Pendiente',
      'diary_mgmt': 'Diario',
      'category': 'Categoría',
      'male': 'Hombre',
      'female': 'Mujer',
      'diary_code': 'Código de Diario',
      'diary_ref': 'Ref. de Diario',
      'save_booking': 'Guardar',
      'export_settings': 'Ajustes de Exportación',
      'show_names': 'Mostrar Nombres',
      'show_phone': 'Mostrar Teléfono',
      'show_address': 'Mostrar Dirección',
      'show_diary': 'Mostrar Ref. de Diario',
      'screenshot_4k': 'Captura 4K',
      'share_image': 'Compartir como Imagen',
      'full_report': 'Generar Informe',
      'generating_pdf': 'Generando PDF...',
      'app': 'App',
    },
    'fr': {
      'delete_booking_q': 'Supprimer la réservation ?',
      'no_image_card': 'PAS DE CARTE D\'IMAGE',
      'due': 'Dû',
      'paid': 'Payé',
      'booking_confirmed_title': 'Réservation confirmée',
      'not_applicable': 'N/A',
      'address': 'Adresse',
      'contact': 'Contact',
      'financials': 'Détails financiers',
      'total': 'Total',
      'received': 'Reçu',
      'thank_you': 'Merci',
      'selected': 'Sélectionné',
      'auth_reason': 'Authentifiez-vous pour accéder à l\'application',
      'face_id': 'Face ID',
      'fingerprint': 'Empreinte digitale',
      'iris': 'Iris',
      'biometric': 'Biométrique',

      'select_business_type': 'Sélectionner le type d\'entreprise',
      'BUSINESS': 'ENTREPRISE',
      'APPEARANCE': 'APPARENCE',
      'dark_mode': 'Mode sombre',
      'ABOUT': 'À PROPOS',
      'version': 'Version',
      'privacy_policy': 'Politique de confidentialité',
      'licenses': 'Licences',
      'github': 'GitHub',
      'EXPORT': 'EXPORTER',
      'manage_pdf_layout': 'Gérer la mise en page et la qualité du PDF',
      'SECURITY': 'SÉCURITÉ',
      'app_lock_biometrics': 'Verrouillage d\'application (Biométrie)',
      'enable_biometric': 'Activer l\'empreinte digitale ou le déverrouillage du visage',
      'biometrics_unavailable': 'Biométrie non disponible sur cet appareil',
      'BACKUP & SYNC': 'SAUVEGARDE & SYNCHRONISATION',
      'export_backup': 'Exporter la sauvegarde',
      'import_backup': 'Importer la sauvegarde',
      'auto_backup': 'Sauvegarde automatique',
      'import_backup_warning': 'Cela fusionnera les réservations avec la liste actuelle.',
      'HELP': 'AIDE',
      'fps_monitor': 'Moniteur FPS',
      'promotion_120hz': 'ProMotion (120Hz)',
      'saved_successfully': 'Enregistré avec succès',
      'customer_information': 'Informations client',
      'finance_details': 'Détails financiers',
      'business_insights': 'Aperçu de l\'entreprise',
      'monthly_performance': 'Performance mensuelle',
      'total_valuation': 'ÉVALUATION TOTALE',
      'events_count': 'Événements',
      'collected': 'Collecté',
      'outstanding': 'En suspens',

      'delete_bookings': 'Supprimer les réservations ?',
      'cannot_undo': 'Cette action est irréversible.',
      'cancel': 'Annuler',
      'share_text': 'Partager le texte (WhatsApp/Autre)',
      'share_image_card': 'Partager l\'image de la carte',
      'change_to': 'Changer pour',
      'change': 'Changer',
      'business_changed': 'Type d\'entreprise modifié',
      'restore_backup': 'Restaurer la sauvegarde ?',
      'import': 'Importer',
      'enable': 'Activer',
      'developer_options': 'Options de développement',
      'close': 'Fermer',
      'contact_details': 'Coordonnées',
      'select_wedding_dates': 'Veuillez sélectionner les dates',
      'internal_notes': 'Notes internes...',
      'advance_paid': 'Acompte Payé',
      'pending': 'En attente',
      'saved': 'Enregistré !',
      'new_booking': 'Nouvelle Réservation',
      'edit_booking': 'Modifier Réservation',
      'error': 'Erreur',

      'app_locked': 'App Verrouillée',
      'authenticating': 'Authentification...',
      'unlock_continue': 'Déverrouillez pour continuer',
      'tap_to_unlock': 'Touchez pour déverrouiller avec',

      'help_create_title': 'Crear una Reserva',
      'help_create_content': 'Toque el botón + para crear una reserva.',
      'help_create_step1': 'Toque el botón +',
      'help_create_step2': 'Ingrese el nombre',
      'help_create_step3': 'Seleccione fechas',
      'help_create_step4': 'Agregue finanzas',
      'help_create_step5': 'Toque HECHO',
      'help_biz_title': 'Tipos de Negocio',
      'help_biz_content': 'Soporta múltiples tipos de negocio.',
      'help_biz_step1': 'Ajustes',
      'help_biz_step2': 'Elija el tipo',
      'help_biz_step3': 'Confirme',
      'help_calc_title': 'Cálculos',
      'help_calc_content': 'Rastree pagos con impuestos.',
      'help_calc_step1': 'Agregue el total',
      'help_calc_step2': 'Agregue el anticipo',
      'help_calc_step3': 'Calcula saldo',
      'help_share_title': 'Compartir',
      'help_share_content': 'Exporte reservas como PDF.',
      'help_share_step1': 'Abra una reserva',
      'help_share_step2': 'Toque compartir',
      'help_share_step3': 'Elija formato',
      'help_dark_title': 'Modo Oscuro',
      'help_dark_content': 'Cambie temas.',
      'help_dark_step1': 'Ajustes',
      'help_dark_step2': 'Active Modo Oscuro',
      'help_backup_title': 'Sauvegarde & Restauration',
      'help_backup_content': 'Sauvegardez vos données localement ou synchronisez-les avec Google Drive.',
      'help_backup_step1': 'Allez dans Paramètres > Sauvegarde & Synchro',
      'help_backup_step2': 'Appuyez sur "Exporter la sauvegarde" pour enregistrer localement.',
      'help_backup_step3': 'Appuyez sur "Sauvegarder sur Drive" pour enregistrer dans le cloud.',
      'help_backup_step4': 'Pour restaurer, appuyez sur "Importer" ou "Restaurer depuis Drive".',
      'vownote': 'BizLedger',
      'search': 'Buscar...',
      'no_bookings': 'No hay reservas',
      'completed': 'Completado',
      'address': 'Dirección',
      'phone': 'Teléfono',
      'dates': 'Fechas',
      'total': 'Total',
      'received': 'Recibido',
      'due': 'Saldo',
      'done': 'Hecho',
      'delete': 'Eliminar',
      'export_pdf': 'Exportar PDF',
      'customer': 'Cliente',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'money_in_pdf': 'Mostrar Dinero en PDF',
      'help_center': 'Centro de Ayuda',
      'help_text': 'Aprende a usar BizLedger.',
      'bride': 'Novia',
      'groom': 'Novio',
      'alt_phone': 'Teléfono Alt',
      'notes': 'Notas',
      'total_adv': 'Anticipo Total',
      'adv_received': 'Anticipo Recibido',
      'adv_pending': 'Anticipo Pendiente',
      'diary_mgmt': 'Diario',
      'category': 'Categoría',
      'male': 'Hombre',
      'female': 'Mujer',
      'diary_code': 'Código de Diario',
      'diary_ref': 'Ref. de Diario',
      'save_booking': 'Guardar',
      'export_settings': 'Ajustes de Exportación',
      'show_names': 'Mostrar Nombres',
      'show_phone': 'Mostrar Teléfono',
      'show_address': 'Mostrar Dirección',
      'show_diary': 'Mostrar Ref. de Diario',
      'screenshot_4k': 'Captura 4K',
      'share_image': 'Compartir como Imagen',
      'full_report': 'Generar Informe',
      'generating_pdf': 'Generando PDF...',
      'app': 'App',
    },
    'ar': {
      'Wedding Studio': 'استوديو الزفاف',
      'Photography Studio': 'استوديو التصوير',
      'Catering Service': 'خدمة الضيافة والطعام',
      'Event Planning': 'تخطيط الفعاليات',
      'General Business': 'عمل عام',
      'Wedding Report': 'تقرير الزفاف',
      'Photography Report': 'تقرير التصوير',
      'Catering Report': 'تقرير الضيافة',
      'Event Report': 'تقرير الفعالية',
      'Business Report': 'تقرير العمل',
      'Wedding Dates': 'تواريخ الزفاف',
      'Session Dates': 'تواريخ الجلسات',
      'Service Dates': 'تواريخ الخدمة',
      'Event Dates': 'تواريخ الفعاليات',
      'Wedding Date': 'تاريخ الزفاف',
      'Session Date': 'تاريخ الجلسة',
      'Service Date': 'تاريخ الخدمة',
      'Event Date': 'تاريخ الفعالية',
      'Partner Name': 'اسم الشريك',
      'Contact Person': 'شخص الاتصال',
      'Secondary Contact': 'اتصال ثانوي',
      'Organizer': 'المنظم',
      'Co-Organizer': 'منظم مشارك',
      'No weddings booked yet.\nTap + to create your first booking.': 'لم يتم حجز أي حفلات زفاف بعد.\nانقر على + لإنشاء أول حجز لك.',
      'No photoshoots booked yet.\nTap + to schedule your first session.': 'لم يتم حجز أي جلسات تصوير بعد.\nانقر على + لجدولة جلستك الأولى.',
      'No catering orders yet.\nTap + to add your first booking.': 'لا توجد طلبات ضيافة بعد.\nانقر على + لإضافة أول حجز لك.',
      'No events planned yet.\nTap + to create your first event.': 'لم يتم التخطيط لأي فعاليات بعد.\nانقر على + لإنشاء فعاليتك الأولى.',
      'No bookings yet.\nTap + to create your first booking.': 'لا توجد حجوزات بعد.\nانقر على + لإنشاء أول حجز لك.',
      'add_date': 'إضافة تاريخ',
      'required': 'مطلوب',
      'gdrive_sync': 'مزامنة جوجل درايف',
      'gdrive_desc': 'نسخ قاعدة البيانات احتياطيًا بأمان إلى حسابك الشخصي في Google Drive (AppData)',
      'sign_in_google': 'تسجيل الدخول باستخدام جوجل',
      'sign_out': 'تسجيل الخروج',
      'backup_to_drive': 'نسخ احتياطي إلى درايف',
      'restore_from_drive': 'استعادة من درايف',
      'connected_as': 'متصل كـ',
      'backup_success': 'تم رفع النسخة الاحتياطية بنجاح!',
      'restore_success': 'اكتملت الاستعادة! يرجى إعادة تشغيل التطبيق.',
      'error_backup': 'فشل النسخ الاحتياطي',
      'error_restore': 'فشلت الاستعادة',
      'business_type': 'نوع العمل',

      'delete_booking_q': 'هل تريد حذف الحجز؟',
      'no_image_card': 'لا توجد بطاقة صور',
      'due': 'مستحق',
      'paid': 'مدفوع',
      'booking_confirmed_title': 'تم تأكيد الحجز',
      'not_applicable': 'غير ينطبق',
      'address': 'العنوان',
      'contact': 'الاتصال',
      'financials': 'المالية',
      'total': 'الإجمالي',
      'received': 'المستلم',
      'thank_you': 'شكرًا لك',
      'selected': 'محدد',
      'auth_reason': 'الرجاء التحقق للوصول إلى التطبيق',
      'face_id': 'بصمة الوجه',
      'fingerprint': 'بصمة الإصبع',
      'iris': 'بصمة العين',
      'biometric': 'البيومترية',

      'select_business_type': 'اختر نوع العمل',
      'BUSINESS': 'العمل',
      'APPEARANCE': 'المظهر',
      'dark_mode': 'الوضع الداكن',
      'ABOUT': 'حول',
      'version': 'الإصدار',
      'privacy_policy': 'سياسة الخصوصية',
      'licenses': 'التراخيص',
      'github': 'GitHub',
      'EXPORT': 'تصدير',
      'manage_pdf_layout': 'إدارة تخطيط وجودة PDF',
      'SECURITY': 'الأمان',
      'app_lock_biometrics': 'قفل التطبيق (البيومترية)',
      'enable_biometric': 'تمكين بصمة الإصبع أو التعرف على الوجه',
      'biometrics_unavailable': 'المؤشرات الحيوية غير متوفرة على هذا الجهاز',
      'BACKUP & SYNC': 'النسخ الاحتياطي والمزامنة',
      'export_backup': 'تصدير النسخة الاحتياطية',
      'import_backup': 'استيراد النسخة الاحتياطية',
      'auto_backup': 'النسخ الاحتياطي التلقائي',
      'import_backup_warning': 'سيؤدي هذا إلى دمج الحجوزات مع القائمة الحالية.',
      'HELP': 'مساعدة',
      'fps_monitor': 'مراقب FPS',
      'promotion_120hz': 'بروموشن (120 هرتز)',
      'saved_successfully': 'تم الحفظ بنجاح',
      'customer_information': 'معلومات العميل',
      'finance_details': 'تفاصيل التمويل',
      'business_insights': 'رؤى الأعمال',
      'monthly_performance': 'الأداء الشهري',
      'total_valuation': 'إجمالي التقييم',
      'events_count': 'فعاليات',
      'collected': 'المحصل',
      'outstanding': 'المستحق',

      'Bride': 'عروس',
      'Groom': 'عريس',
      'BizLedger': 'بيز ليدجر',
      'PhotoLedger': 'فوتو ليدجر',
      'FoodLedger': 'فود ليدجر',
      'EventLedger': 'إيفينت ليدجر',
      'Ledger': 'ليدجر',
      'Wedding Studio': 'استوديو زفاف',
      'Photography Studio': 'استوديو تصوير',
      'Catering Service': 'خدمة تقديم الطعام',
      'Event Planning': 'تخطيط الفعاليات',
      'General Business': 'عمل عام',
      'Wedding Dates': 'تواريخ الزفاف',
      'Session Dates': 'تواريخ الجلسات',
      'Event Dates': 'تواريخ الفعاليات',
      'Service Dates': 'تواريخ الخدمة',
      'Wedding Date': 'تاريخ الزفاف',
      'Session Date': 'تاريخ الجلسة',
      'Event Date': 'تاريخ الفعالية',
      'Service Date': 'تاريخ الخدمة',
      'Client': 'عميل',
      'Customer': 'زبون',
      'Client 1': 'عميل 1',
      'Client 2': 'عميل 2',
      'Contact': 'جهة اتصال',
      'Contact 2': 'جهة اتصال 2',
      'Wedding Report': 'تقرير الزفاف',
      'Photography Report': 'تقرير التصوير',
      'Catering Report': 'تقرير تقديم الطعام',
      'Event Report': 'تقرير الفعاليات',
      'General Report': 'تقرير عام',
      'No weddings booked yet. Add your first wedding!': 'لم يتم حجز أي زفاف بعد. أضف زفافك الأول!',
      'No sessions booked yet. Add your first session!': 'لم يتم حجز أي جلسات بعد. أضف جلستك الأولى!',
      'No events booked yet. Add your first event!': 'لم يتم حجز أي فعاليات بعد. أضف فعاليتك الأولى!',
      'No records found. Add your first record!': 'لم يتم العثور على سجلات. أضف سجلك الأول!',

      'delete_bookings': 'حذف الحجوزات؟',
      'cannot_undo': 'لا يمكن التراجع عن هذا الإجراء.',
      'cancel': 'إلغاء',
      'share_text': 'مشاركة النص (WhatsApp/أخرى)',
      'share_image_card': 'مشاركة صورة البطاقة',
      'change_to': 'التغيير إلى',
      'change': 'تغيير',
      'business_changed': 'تم تغيير نوع العمل إلى',
      'restore_backup': 'استعادة النسخة الاحتياطية؟',
      'import': 'استيراد',
      'enable': 'تفعيل',
      'developer_options': 'خيارات المطور',
      'close': 'إغلاق',
      'contact_details': 'بيانات الاتصال',
      'select_wedding_dates': 'الرجاء تحديد التواريخ',
      'internal_notes': 'ملاحظات داخلية...',
      'advance_paid': 'مقدم مدفوع',
      'pending': 'قيد الانتظار',
      'saved': 'تم الحفظ!',
      'new_booking': 'حجز جديد',
      'edit_booking': 'تعديل الحجز',
      'error': 'خطأ',

      'app_locked': 'التطبيق مقفل',
      'authenticating': 'جاري المصادقة...',
      'unlock_continue': 'افتح للمتابعة',
      'tap_to_unlock': 'اضغط للفتح بواسطة',

      'help_create_title': 'Crear una Reserva',
      'help_create_content': 'Toque el botón + para crear una reserva.',
      'help_create_step1': 'Toque el botón +',
      'help_create_step2': 'Ingrese el nombre',
      'help_create_step3': 'Seleccione fechas',
      'help_create_step4': 'Agregue finanzas',
      'help_create_step5': 'Toque HECHO',
      'help_biz_title': 'Tipos de Negocio',
      'help_biz_content': 'Soporta múltiples tipos de negocio.',
      'help_biz_step1': 'Ajustes',
      'help_biz_step2': 'Elija el tipo',
      'help_biz_step3': 'Confirme',
      'help_calc_title': 'Cálculos',
      'help_calc_content': 'Rastree pagos con impuestos.',
      'help_calc_step1': 'Agregue el total',
      'help_calc_step2': 'Agregue el anticipo',
      'help_calc_step3': 'Calcula saldo',
      'help_share_title': 'Compartir',
      'help_share_content': 'Exporte reservas como PDF.',
      'help_share_step1': 'Abra una reserva',
      'help_share_step2': 'Toque compartir',
      'help_share_step3': 'Elija formato',
      'help_dark_title': 'Modo Oscuro',
      'help_dark_content': 'Cambie temas.',
      'help_dark_step1': 'Ajustes',
      'help_dark_step2': 'Active Modo Oscuro',
      'help_backup_title': 'النسخ الاحتياطي والاستعادة',
      'help_backup_content': 'قم بنسخ حجوزاتك احتياطيًا محليًا بشكل آمن أو مزامنتها مع Google Drive.',
      'help_backup_step1': 'اذهب إلى الإعدادات > النسخ الاحتياطي والمزامنة',
      'help_backup_step2': 'اضغط على "تصدير النسخة الاحتياطية" لحفظ البيانات محليًا.',
      'help_backup_step3': 'اضغط على "النسخ الاحتياطي إلى Drive" لحفظها سحابيًا.',
      'help_backup_step4': 'للاستعادة، اضغط على "استيراد" أو "استعادة من Drive".',
      'vownote': 'BizLedger',
      'search': 'Buscar...',
      'no_bookings': 'No hay reservas',
      'completed': 'Completado',
      'address': 'Dirección',
      'phone': 'Teléfono',
      'dates': 'Fechas',
      'total': 'Total',
      'received': 'Recibido',
      'due': 'Saldo',
      'done': 'Hecho',
      'delete': 'Eliminar',
      'export_pdf': 'Exportar PDF',
      'customer': 'Cliente',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'money_in_pdf': 'Mostrar Dinero en PDF',
      'help_center': 'Centro de Ayuda',
      'help_text': 'Aprende a usar BizLedger.',
      'bride': 'Novia',
      'groom': 'Novio',
      'alt_phone': 'Teléfono Alt',
      'notes': 'Notas',
      'total_adv': 'Anticipo Total',
      'adv_received': 'Anticipo Recibido',
      'adv_pending': 'Anticipo Pendiente',
      'diary_mgmt': 'Diario',
      'category': 'Categoría',
      'male': 'Hombre',
      'female': 'Mujer',
      'diary_code': 'Código de Diario',
      'diary_ref': 'Ref. de Diario',
      'save_booking': 'Guardar',
      'export_settings': 'Ajustes de Exportación',
      'show_names': 'Mostrar Nombres',
      'show_phone': 'Mostrar Teléfono',
      'show_address': 'Mostrar Dirección',
      'show_diary': 'Mostrar Ref. de Diario',
      'screenshot_4k': 'Captura 4K',
      'share_image': 'Compartir como Imagen',
      'full_report': 'Generar Informe',
      'generating_pdf': 'Generando PDF...',
      'app': 'App',
    },
    'de': {
      'delete_booking_q': 'Buchung löschen?',
      'no_image_card': 'KEINE BILD-KARTE',
      'due': 'Fällig',
      'paid': 'Bezahlt',
      'booking_confirmed_title': 'Buchung bestätigt',
      'not_applicable': 'N/A',
      'address': 'Adresse',
      'contact': 'Kontakt',
      'financials': 'Finanzen',
      'total': 'Gesamt',
      'received': 'Erhalten',
      'thank_you': 'Danke',
      'selected': 'Ausgewählt',
      'auth_reason': 'Authentifizieren Sie sich, um auf die App zuzugreifen',
      'face_id': 'Face ID',
      'fingerprint': 'Fingerabdruck',
      'iris': 'Iris',
      'biometric': 'Biometrisch',

      'select_business_type': 'Geschäftstyp auswählen',
      'BUSINESS': 'GESCHÄFT',
      'APPEARANCE': 'AUSSEHEN',
      'dark_mode': 'Dunkelmodus',
      'ABOUT': 'ÜBER',
      'version': 'Version',
      'privacy_policy': 'Datenschutz-Bestimmungen',
      'licenses': 'Lizenzen',
      'github': 'GitHub',
      'EXPORT': 'EXPORTIEREN',
      'manage_pdf_layout': 'PDF-Layout & -Qualität verwalten',
      'SECURITY': 'SICHERHEIT',
      'app_lock_biometrics': 'App-Sperre (Biometrie)',
      'enable_biometric': 'Fingerabdruck- oder Gesichtserkennung aktivieren',
      'biometrics_unavailable': 'Biometrie auf diesem Gerät nicht verfügbar',
      'BACKUP & SYNC': 'BACKUP & SYNCHRONISIERUNG',
      'export_backup': 'Backup exportieren',
      'import_backup': 'Backup importieren',
      'auto_backup': 'Automatisches Backup',
      'import_backup_warning': 'Dadurch werden Buchungen mit der aktuellen Liste zusammengeführt.',
      'HELP': 'HILFE',
      'fps_monitor': 'FPS-Monitor',
      'promotion_120hz': 'ProMotion (120Hz)',
      'saved_successfully': 'Erfolgreich gespeichert',
      'customer_information': 'Kundeninformation',
      'finance_details': 'Finanzdetails',
      'business_insights': 'Geschäftseinblicke',
      'monthly_performance': 'Monatliche Leistung',
      'total_valuation': 'GESAMTBEWERTUNG',
      'events_count': 'Ereignisse',
      'collected': 'Eingezogen',
      'outstanding': 'Ausstehend',

      'delete_bookings': 'Buchungen löschen?',
      'cannot_undo': 'Diese Aktion kann nicht rückgängig gemacht werden.',
      'cancel': 'Abbrechen',
      'share_text': 'Text teilen (WhatsApp/Andere)',
      'share_image_card': 'Kartenbild teilen',
      'change_to': 'Ändern zu',
      'change': 'Ändern',
      'business_changed': 'Geschäftstyp geändert in',
      'restore_backup': 'Backup wiederherstellen?',
      'import': 'Importieren',
      'enable': 'Aktivieren',
      'developer_options': 'Entwickleroptionen',
      'close': 'Schließen',
      'contact_details': 'Kontaktdaten',
      'select_wedding_dates': 'Bitte Daten auswählen',
      'internal_notes': 'Interne Notizen...',
      'advance_paid': 'Anzahlung geleistet',
      'pending': 'Ausstehend',
      'saved': 'Gespeichert!',
      'new_booking': 'Neue Buchung',
      'edit_booking': 'Buchung bearbeiten',
      'error': 'Fehler',

      'app_locked': 'App Gesperrt',
      'authenticating': 'Authentifizierung...',
      'unlock_continue': 'Zum Fortfahren entsperren',
      'tap_to_unlock': 'Tippen zum Entsperren mit',

      'help_create_title': 'Crear una Reserva',
      'help_create_content': 'Toque el botón + para crear una reserva.',
      'help_create_step1': 'Toque el botón +',
      'help_create_step2': 'Ingrese el nombre',
      'help_create_step3': 'Seleccione fechas',
      'help_create_step4': 'Agregue finanzas',
      'help_create_step5': 'Toque HECHO',
      'help_biz_title': 'Tipos de Negocio',
      'help_biz_content': 'Soporta múltiples tipos de negocio.',
      'help_biz_step1': 'Ajustes',
      'help_biz_step2': 'Elija el tipo',
      'help_biz_step3': 'Confirme',
      'help_calc_title': 'Cálculos',
      'help_calc_content': 'Rastree pagos con impuestos.',
      'help_calc_step1': 'Agregue el total',
      'help_calc_step2': 'Agregue el anticipo',
      'help_calc_step3': 'Calcula saldo',
      'help_share_title': 'Compartir',
      'help_share_content': 'Exporte reservas como PDF.',
      'help_share_step1': 'Abra una reserva',
      'help_share_step2': 'Toque compartir',
      'help_share_step3': 'Elija formato',
      'help_dark_title': 'Modo Oscuro',
      'help_dark_content': 'Cambie temas.',
      'help_dark_step1': 'Ajustes',
      'help_dark_step2': 'Active Modo Oscuro',
      'help_backup_title': 'Sicherung & Wiederherstellung',
      'help_backup_content': 'Sichern Sie Ihre Buchungen lokal oder synchronisieren Sie sie mit Google Drive.',
      'help_backup_step1': 'Gehen Sie zu Einstellungen > Sicherung & Synchronisierung',
      'help_backup_step2': 'Tippen Sie auf "Sicherung exportieren", um Daten lokal zu speichern.',
      'help_backup_step3': 'Tippen Sie auf "Auf Drive sichern", um Daten in der Cloud zu speichern.',
      'help_backup_step4': 'Tippen Sie zum Wiederherstellen auf "Importieren" oder "Wiederherstellen von Drive".',
      'vownote': 'BizLedger',
      'search': 'Buscar...',
      'no_bookings': 'No hay reservas',
      'completed': 'Completado',
      'address': 'Dirección',
      'phone': 'Teléfono',
      'dates': 'Fechas',
      'total': 'Total',
      'received': 'Recibido',
      'due': 'Saldo',
      'done': 'Hecho',
      'delete': 'Eliminar',
      'export_pdf': 'Exportar PDF',
      'customer': 'Cliente',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'money_in_pdf': 'Mostrar Dinero en PDF',
      'help_center': 'Centro de Ayuda',
      'help_text': 'Aprende a usar BizLedger.',
      'bride': 'Novia',
      'groom': 'Novio',
      'alt_phone': 'Teléfono Alt',
      'notes': 'Notas',
      'total_adv': 'Anticipo Total',
      'adv_received': 'Anticipo Recibido',
      'adv_pending': 'Anticipo Pendiente',
      'diary_mgmt': 'Diario',
      'category': 'Categoría',
      'male': 'Hombre',
      'female': 'Mujer',
      'diary_code': 'Código de Diario',
      'diary_ref': 'Ref. de Diario',
      'save_booking': 'Guardar',
      'export_settings': 'Ajustes de Exportación',
      'show_names': 'Mostrar Nombres',
      'show_phone': 'Mostrar Teléfono',
      'show_address': 'Mostrar Dirección',
      'show_diary': 'Mostrar Ref. de Diario',
      'screenshot_4k': 'Captura 4K',
      'share_image': 'Compartir como Imagen',
      'full_report': 'Generar Informe',
      'generating_pdf': 'Generando PDF...',
      'app': 'App',
    },
    'id': {
      'delete_bookings': 'Hapus Pemesanan?',
      'cannot_undo': 'Tindakan ini tidak dapat dibatalkan.',
      'cancel': 'Batal',
      'share_text': 'Bagikan Teks (WhatsApp/Lainnya)',
      'share_image_card': 'Bagikan Gambar Kartu',
      'change_to': 'Ubah ke',
      'change': 'Ubah',
      'business_changed': 'Jenis bisnis diubah ke',
      'restore_backup': 'Pulihkan Cadangan?',
      'import': 'Impor',
      'enable': 'Aktifkan',
      'developer_options': 'Opsi Pengembang',
      'close': 'Tutup',
      'contact_details': 'Detail kontak',
      'select_wedding_dates': 'Silakan pilih tanggal',
      'internal_notes': 'Catatan internal...',
      'advance_paid': 'Uang Muka Dibayar',
      'pending': 'Tertunda',
      'saved': 'Tersimpan!',
      'new_booking': 'Pemesanan Baru',
      'edit_booking': 'Edit Pemesanan',
      'error': 'Kesalahan',

      'app_locked': 'Aplikasi Terkunci',
      'authenticating': 'Mengautentikasi...',
      'unlock_continue': 'Buka kunci untuk melanjutkan',
      'tap_to_unlock': 'Ketuk untuk membuka dengan',

      'help_create_title': 'Crear una Reserva',
      'help_create_content': 'Toque el botón + para crear una reserva.',
      'help_create_step1': 'Toque el botón +',
      'help_create_step2': 'Ingrese el nombre',
      'help_create_step3': 'Seleccione fechas',
      'help_create_step4': 'Agregue finanzas',
      'help_create_step5': 'Toque HECHO',
      'help_biz_title': 'Tipos de Negocio',
      'help_biz_content': 'Soporta múltiples tipos de negocio.',
      'help_biz_step1': 'Ajustes',
      'help_biz_step2': 'Elija el tipo',
      'help_biz_step3': 'Confirme',
      'help_calc_title': 'Cálculos',
      'help_calc_content': 'Rastree pagos con impuestos.',
      'help_calc_step1': 'Agregue el total',
      'help_calc_step2': 'Agregue el anticipo',
      'help_calc_step3': 'Calcula saldo',
      'help_share_title': 'Compartir',
      'help_share_content': 'Exporte reservas como PDF.',
      'help_share_step1': 'Abra una reserva',
      'help_share_step2': 'Toque compartir',
      'help_share_step3': 'Elija formato',
      'help_dark_title': 'Modo Oscuro',
      'help_dark_content': 'Cambie temas.',
      'help_dark_step1': 'Ajustes',
      'help_dark_step2': 'Active Modo Oscuro',
      'help_backup_title': 'Cadangan & Pulihkan',
      'help_backup_content': 'Cadangkan data pemesanan secara lokal atau sinkronkan ke Google Drive.',
      'help_backup_step1': 'Buka Pengaturan > Cadangan & Sinkronisasi',
      'help_backup_step2': 'Ketuk "Ekspor Cadangan" untuk menyimpan data di perangkat.',
      'help_backup_step3': 'Ketuk "Cadangkan ke Drive" untuk mengunggah ke cloud.',
      'help_backup_step4': 'Untuk memulihkan, ketuk "Impor" atau "Pulihkan dari Drive".',
      'vownote': 'BizLedger',
      'search': 'Buscar...',
      'no_bookings': 'No hay reservas',
      'completed': 'Completado',
      'address': 'Dirección',
      'phone': 'Teléfono',
      'dates': 'Fechas',
      'total': 'Total',
      'received': 'Recibido',
      'due': 'Saldo',
      'done': 'Hecho',
      'delete': 'Eliminar',
      'export_pdf': 'Exportar PDF',
      'customer': 'Cliente',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'money_in_pdf': 'Mostrar Dinero en PDF',
      'help_center': 'Centro de Ayuda',
      'help_text': 'Aprende a usar BizLedger.',
      'bride': 'Novia',
      'groom': 'Novio',
      'alt_phone': 'Teléfono Alt',
      'notes': 'Notas',
      'total_adv': 'Anticipo Total',
      'adv_received': 'Anticipo Recibido',
      'adv_pending': 'Anticipo Pendiente',
      'diary_mgmt': 'Diario',
      'category': 'Categoría',
      'male': 'Hombre',
      'female': 'Mujer',
      'diary_code': 'Código de Diario',
      'diary_ref': 'Ref. de Diario',
      'save_booking': 'Guardar',
      'export_settings': 'Ajustes de Exportación',
      'show_names': 'Mostrar Nombres',
      'show_phone': 'Mostrar Teléfono',
      'show_address': 'Mostrar Dirección',
      'show_diary': 'Mostrar Ref. de Diario',
      'screenshot_4k': 'Captura 4K',
      'share_image': 'Compartir como Imagen',
      'full_report': 'Generar Informe',
      'generating_pdf': 'Generando PDF...',
      'app': 'App',
    },
    'pt': {
      'delete_bookings': 'Apagar Reservas?',
      'cannot_undo': 'Esta ação não pode ser desfeita.',
      'cancel': 'Cancelar',
      'share_text': 'Compartilhar Texto (WhatsApp/Outros)',
      'share_image_card': 'Compartilhar Imagem',
      'change_to': 'Mudar para',
      'change': 'Mudar',
      'business_changed': 'Tipo de negócio alterado para',
      'restore_backup': 'Restaurar Backup?',
      'import': 'Importar',
      'enable': 'Ativar',
      'developer_options': 'Opções de Desenvolvedor',
      'close': 'Fechar',
      'contact_details': 'Detalhes de contato',
      'select_wedding_dates': 'Selecione as datas',
      'internal_notes': 'Notas internas...',
      'advance_paid': 'Sinal Pago',
      'pending': 'Pendente',
      'saved': 'Salvo!',
      'new_booking': 'Nova Reserva',
      'edit_booking': 'Editar Reserva',
      'error': 'Erro',

      'app_locked': 'App Bloqueado',
      'authenticating': 'Autenticando...',
      'unlock_continue': 'Desbloqueie para continuar',
      'tap_to_unlock': 'Toque para desbloquear com',

      'help_create_title': 'Crear una Reserva',
      'help_create_content': 'Toque el botón + para crear una reserva.',
      'help_create_step1': 'Toque el botón +',
      'help_create_step2': 'Ingrese el nombre',
      'help_create_step3': 'Seleccione fechas',
      'help_create_step4': 'Agregue finanzas',
      'help_create_step5': 'Toque HECHO',
      'help_biz_title': 'Tipos de Negocio',
      'help_biz_content': 'Soporta múltiples tipos de negocio.',
      'help_biz_step1': 'Ajustes',
      'help_biz_step2': 'Elija el tipo',
      'help_biz_step3': 'Confirme',
      'help_calc_title': 'Cálculos',
      'help_calc_content': 'Rastree pagos con impuestos.',
      'help_calc_step1': 'Agregue el total',
      'help_calc_step2': 'Agregue el anticipo',
      'help_calc_step3': 'Calcula saldo',
      'help_share_title': 'Compartir',
      'help_share_content': 'Exporte reservas como PDF.',
      'help_share_step1': 'Abra una reserva',
      'help_share_step2': 'Toque compartir',
      'help_share_step3': 'Elija formato',
      'help_dark_title': 'Modo Oscuro',
      'help_dark_content': 'Cambie temas.',
      'help_dark_step1': 'Ajustes',
      'help_dark_step2': 'Active Modo Oscuro',
      'help_backup_title': 'Backup & Restauração',
      'help_backup_content': 'Faça backup de seus agendamentos localmente ou sincronize com o Google Drive.',
      'help_backup_step1': 'Vá para Configurações > Backup & Sincronização',
      'help_backup_step2': 'Toque em "Exportar Backup" para salvar no dispositivo.',
      'help_backup_step3': 'Toque em "Backup no Drive" para salvar na nuvem.',
      'help_backup_step4': 'Para restaurar, toque em "Importar" ou "Restaurar do Drive".',
      'vownote': 'BizLedger',
      'search': 'Buscar...',
      'no_bookings': 'No hay reservas',
      'completed': 'Completado',
      'address': 'Dirección',
      'phone': 'Teléfono',
      'dates': 'Fechas',
      'total': 'Total',
      'received': 'Recibido',
      'due': 'Saldo',
      'done': 'Hecho',
      'delete': 'Eliminar',
      'export_pdf': 'Exportar PDF',
      'customer': 'Cliente',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'money_in_pdf': 'Mostrar Dinero en PDF',
      'help_center': 'Centro de Ayuda',
      'help_text': 'Aprende a usar BizLedger.',
      'bride': 'Novia',
      'groom': 'Novio',
      'alt_phone': 'Teléfono Alt',
      'notes': 'Notas',
      'total_adv': 'Anticipo Total',
      'adv_received': 'Anticipo Recibido',
      'adv_pending': 'Anticipo Pendiente',
      'diary_mgmt': 'Diario',
      'category': 'Categoría',
      'male': 'Hombre',
      'female': 'Mujer',
      'diary_code': 'Código de Diario',
      'diary_ref': 'Ref. de Diario',
      'save_booking': 'Guardar',
      'export_settings': 'Ajustes de Exportación',
      'show_names': 'Mostrar Nombres',
      'show_phone': 'Mostrar Teléfono',
      'show_address': 'Mostrar Dirección',
      'show_diary': 'Mostrar Ref. de Diario',
      'screenshot_4k': 'Captura 4K',
      'share_image': 'Compartir como Imagen',
      'full_report': 'Generar Informe',
      'generating_pdf': 'Generando PDF...',
      'app': 'App',
    },
  };

  String get currentLanguage => _currentLang;

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLang = prefs.getString(_langKey) ?? 'en';
  }

  Future<void> setLanguage(String lang) async {
    _currentLang = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_langKey, lang);
    notifyListeners();
  }

  String tr(String key) {
    return _translations[_currentLang]?[key] ?? key;
  }
}

String tr(String key) => LocalizationService().tr(key);
